.github/workflows/tests.yml
capa/features/extractors/viv/__init__.py
capa/features/freeze.py
capa/main.py
capa/render/__init__.py
doc/installation.md
scripts/capafmt.py
scripts/lint.py
scripts/migrate-rules.py
scripts/show-capabilities-by-function.py
scripts/show-features.py
tests/test_freeze.py
tests/test_main.py
tests/test_viv_features.py

Run isort 5 and black for every pull request or push.
You can see this working in [Ana06/capa](https://github.com/Ana06/capa/pull/1)
The idea is to add jobs to the same action for rule linter and tests and to show a badge in the README with the status of the workflow (the name of the badge is the same as the workflow - `CI`). See https://github.com/fireeye/capa/pull/151
Closes https://github.com/fireeye/capa/issues/75
Closes https://github.com/fireeye/capa/issues/76

ci: Add GitHub action for style checkers

---

.github/workflows/tests.yml
scripts/lint.py

- Prevent the linter to raise an exception if `examples` is `None`, as it for example currently happens in: `capa-rules/nursery/hash-data-using-murmur2.yml`. We could also remove the `examples` tag in those cases, but the linter shouldn't break in any case.
- Add the rule linter to the CI GitHub action. A similar actions should be added to [capa-rules](https://github.com/fireeye/capa-rules) as well (WIP in https://github.com/fireeye/capa-rules/pull/39)

Fix rule linter and run it in the CI GitHub action

---

.github/workflows/tests.yml
README.md
doc/installation.md
setup.py

- Vivisect is not available on PyPI. Tell `pip` in `setup.py` where to find it so that it is not needed to do it as a separate step.
- Add the tests to the CI GitHub action. Only run the tests if code style and rule linter succeed, as tests take some time to run. A similar actions should be added to `capa-testfiles`. Tests fail in this PR because they are broken in master: https://github.com/fireeye/capa/issues/174
- Update CI badge in README

Add vivisect installation to setup & Add tests to GitHub Actions

---

capa/render/default.py

Having the sha1 & sha256 hashes by default would actually be pretty useful I think. This change would add those.

add sha1/sha256 to default renderer

---

capa/main.py

when the source directory is not writable, don't bail out - just use the .viv in memory. this means that re-running will not be able to reuse the analysis, but i think the simplicity of this is probably ok.
closes #168

main: don't crash when the .viv cannot be saved

---

capa/features/extractors/helpers.py
capa/features/extractors/ida/insn.py
capa/features/extractors/viv/insn.py
scripts/import-to-bn.py
scripts/lint.py
scripts/show-features.py
tests/test_ida_features.py
tests/test_viv_features.py

codifies our decision to support offset features with negative values #197 by relaxing the lint and updating the IDA extractor.
in order to demonstrate that the IDA changes work, i implemented tests for the IDA extractor. these will not run during CI, but we can invoke them manually during development. they should be run with the `mimikatz.exe_` database open.
closes #197 
closes #202

support negative offset features (and add IDA tests)

---

capa/engine.py
capa/render/__init__.py
capa/render/vverbose.py
capa/rules.py
tests/test_engine.py
tests/test_rules.py

Enable descriptions for statement nodes such as `and` and `or`. Includes some refactoring to facilitate the implementation.
Use of case in: fireeye/capa-rules/pull/51
Closes https://github.com/fireeye/capa/issues/194

 Enable descriptions for statement nodes

---

capa/features/__init__.py
capa/features/extractors/ida/insn.py
capa/features/extractors/viv/insn.py
capa/features/file.py
capa/features/insn.py
capa/rules.py
tests/test_engine.py
tests/test_ida_features.py
tests/test_rules.py
tests/test_viv_features.py

I added the arch flavor directly to the `Feature` base class since this meant the smallest delta and duplication of code. In theory, this means we could add arch-specific strings/regex/bytes/mnemonics/etc. easily; however, we don't have any plans to do so. In this PR, the freeze format is extended a bit - kwargs to the Feature constructors end up in a final dictionary "argument". This is not a breaking change. 
closes #210

rules: add support for arch flavors of Number and Offset features

---

capa/ida/explorer/model.py

Adding support to display new architecture decorator for `number` and `offset` features:

explorer: adding support to display arch decorator on numbers/offsets

---

capa/features/extractors/__init__.py
capa/features/extractors/ida/function.py
capa/features/extractors/ida/helpers.py
capa/features/extractors/viv/function.py
capa/ida/explorer/model.py
capa/rules.py
tests/test_freeze.py
tests/test_ida_features.py
tests/test_main.py
tests/test_rules.py
tests/test_viv_features.py

Get rid of the `characteristic(switch)` feature as any of our rules use it and its analysis is not very easy. Analysis results most likely differ across backends, leading to inconsistency. :bowtie: 
Closes https://github.com/fireeye/capa/issues/231

extractor: remove characteristic(switch)

---

.github/workflows/build.yml

The build workflow is currently broken due to the release of pyinstaller 4 which doesn't support Python 2.7. Fix pyinstaller to version 3 to fix it.
Zip binaries before uploading them to the release to be able to keep the executable flag. To do this I am using `actions/upload-artifact` to upload every of the binaries and `actions/download-artifact` to download them in ubuntu-latest. By doing this, we can zip all the binaries in the same way. The only disadvantage is that the executable flag gets lost in the upload/download and we need to set it again.
At first I wanted to use [`montudor/action-zip`](https://github.com/montudor/action-zip)  for this, but then I realised that `zip` is install in the used ubuntu image. 
You can see it working here: …

Fix build workflow & zip binaries

---

.github/workflows/tests.yml
capa/features/freeze.py
tests/fixtures.py
tests/test_freeze.py
tests/test_main.py
tests/test_viv_features.py

backport py3 testing enhancements from #234. basically: wrap py2-only things in xfail annotations.
when we add a py3 backend, then all we need to do is update `fixtures::get_extractor()` to return the py3 backend on py3 and then re-run the tests. pytest will complain that things that we used to fail no longer fail, so go through and remove those xfail marks.

backport py3 testing enhancements

---

capa/features/extractors/ida/__init__.py
capa/features/extractors/ida/helpers.py
capa/features/extractors/ida/insn.py

Fixes #237.
Adds additional `nzxor` stack cookie check for IDA extractor modeled after viv extractor. Previous code relied on IDA analysis to add stack/security-related comments to the corresponding instruction. IDA fails to do this for the function referenced in #237 so these checks fail.
`test_ida_features` now passing `nzxor` check IDA on 7.4/7.5 for Python 2/3 🚀:
```
...
OK   mimikatz-function=0x410DFC-characteristic(nzxor)-True
OK   mimikatz-function=0x40105D-characteristic(nzxor)-False
OK   mimikatz-function=0x46D534-characteristic(nzxor)-False
...
```

add additional nzxor stack cookie check for IDA extractor

---

setup.py

Fixes #256 - capa requires halo==0.0.30, which has a dependency on
spinners>=0.0.24. spinners 0.0.24 has a dependency on enum34==1.1.6,
but 1.1.10 gets installed and used on my machine without the version
being pinned to 1.1.6. This issue occurs when using python 2.7.

Fix 256: Pin enum34 version to 1.1.6 for python2.7

---

.gitmodules

Fixes #255
This enables both HTTPS and SSH to be used to checkout
the project, per https://stackoverflow.com/a/44630028/9457431

Fix #255: Use relative paths for the git submodule

---

capa/ida/explorer/model.py

Adds code to explorer plugin to display statement descriptions in UI:

explorer: display statement descriptions

---

capa/ida/explorer/view.py
capa/ida/ida_capa_explorer.py

Rule information is collapsed by default and *Address* column is populated only at the first expansion layer.
There is no easy way to expand all results and *Address* column is very convenient to navigate to match locations. Setting expansion by default to 1 level so that match location addresses are shown to make navigation faster.

Set Tree View default expansion to 1 level

---

capa/ida/plugin/form.py
capa/ida/plugin/proxy.py
capa/ida/plugin/view.py

add search bar to IDA plugin that lets a user filter the rule matches by a given term. matches against any term in the match, including rule name and feature name or value.
this filter is chained after the "limit results to current function" so these work probably as you'd expect.
before:
query `file`:
query `subscope`:
closes #212

ida plugin: add search bar

---

capa/features/extractors/ida/helpers.py
capa/features/extractors/ida/insn.py

Check whether the auto-analyser (or user) has marked an operand as an offset, instead of checking whether the value is mapped.

Fix #280: Test if op is an offset

---

capa/ida/plugin/form.py

if the rule path that was saved via settings doesn't exist, re-prompt the user for their rules path.
closes #298

ida plugin: don't use rule path settings if the path doesn't exist

---

capa/ida/plugin/__init__.py
capa/ida/plugin/form.py
capa/ida/plugin/model.py

Brings new improvements to IDA plugin:
improvements:
* new `Analyze` and `Reset` buttons added to UI - quick access to run analysis and reset plugin and IDA user interfaces
* removes `Rerun analysis` and `View` options from menu bar
* plugin does not run database analysis automatically when started - better matches life cycle of a plugin versus script
* users must explicitily run database analysis using `Analyze` button
* font color of `Address` column and IDA highlight color updated to match capa logo
* UI controls disabled until analysis has been performed
* additional messages added to status label - help guide users when interacting with plugin
* remove unnecessary debug printing
* remove unused code

ida plugin: ui improvements

---

.github/workflows/build.yml
.github/workflows/tests.yml
capa/rules.py

use PyYAML CLoader to parse rules when available

---

capa/features/extractors/ida/file.py
tests/fixtures.py
tests/test_ida_features.py

if name and ordinal are present provide both of these import features

extract ordinal and name imports

---

setup.py

Most importantly this adds capa's readme as long description for PyPI. Need to test how this actually works out before/with next major release.

add long description and other improvements

---

.github/workflows/tests.yml
README.md
capa/features/extractors/smda/__init__.py
capa/features/extractors/smda/basicblock.py
capa/features/extractors/smda/file.py
capa/features/extractors/smda/function.py
capa/features/extractors/smda/insn.py
capa/main.py
setup.py
tests/fixtures.py
tests/test_main.py
tests/test_smda_features.py

Hey all!
We propose to integrate [SMDA](https://github.com/danielplohmann/smda) as a disassembler backend into capa to enable full Python 3 support.
SMDA is a lightweight and fast recursive disassembler built on top of [capstone](https://github.com/aquynh/capstone), covering PE and ELF files in 32/64bit. It is compatible with both Python 2 and Python 3.
The pull request contains an implementation structurally oriented along the vivisect implementation and provides all capa-features covered by vivisect. We also made sure that the code is in line with the style requirements and has full test coverage using the `tests/fixtures.get_extractor()` method:
This initial PR sets SMDA as a default backend for Python 3. 
This choice was made to allow you an easier evaluation of the contribution. 
As …

initial commit for backend-smda

---

capa/features/extractors/viv/insn.py
tests/fixtures.py

like
```asm
lea     eax, aExampleString
```

fix: add viv extract strings for i386ImmMemOper operands

---

capa/features/extractors/ida/insn.py
capa/features/extractors/smda/insn.py
capa/features/extractors/viv/insn.py
tests/fixtures.py

- cover more XOR instructions
- force vivisect function at FVA in tests

add more xor instructions

---

capa/features/extractors/helpers.py

```
Traceback (most recent call last):
File "/opt/CAPE/utils/../lib/cuckoo/common/cape_utils.py", line 223, in flare_capa_details
capabilities, counts = capa.main.find_capabilities(rules, extractor, disable_progress=True)
File "/usr/local/lib/python2.7/dist-packages/capa/main.py", line 116, in find_capabilities
function_matches, bb_matches, feature_count = find_function_capabilities(ruleset, extractor, f)
File "/usr/local/lib/python2.7/dist-packages/capa/main.py", line 68, in find_function_capabilities
for feature, va in extractor.extract_insn_features(f, bb, insn):
File "/usr/local/lib/python2.7/dist-packages/capa/features/extractors/viv/__init__.py", line 84, in extract_insn_features
for feature, va in capa.features.extractors.viv.insn.extract_features(f, bb, insn):
File …
```

fix is_ordinal IndexError

---

capa/main.py

TODO it still may show the below in some instances; haven't been able to disable this yet
`WARNING:envi:i386RegOper needs to implement getOperAddr!`
For example on `3b13b6f1d7cd14dc4a097a12e2e505c0a4cff495262261e2bfc991df238b9b04.dll_`
```
$ capa 3b13b6f1d7cd14dc4a097a12e2e505c0a4cff495262261e2bfc991df238b9b04 .dll_
loading : 100%|████████████████████████████████████████████████████████████████████████████████████████████| 433/433 [00:01<00:00, 324.81     rules/s]
... analyzing programWARNING:envi:i386RegOper needs to implement getOperAddr!
WARNING:envi:i386RegOper needs to implement getOperAddr!
```

set level of more viv loggers explicitly

---

scripts/lint.py

expected lib path created issues when running the linter in the current directory `.`

adjust expected lib path and log time

---

capa/rules.py
scripts/capafmt.py
scripts/lint.py

- changes to arrive at the desired yaml rule format
- capafmt option to only check differences
- linter updates to ensure right yaml formatting
The changes in https://github.com/fireeye/capa-rules/pull/230 have been performed using the updated `capafmt` script included here.
closes #313

Lint rule formatting and improved rule dump

---

scripts/show-capabilities-by-function.py
scripts/show-features.py

Enable use of multiple backends in `show-features.py`, similar to `show-capabilities-by-function.py`. Also, removing `viv` dependency from `show-capabilities-by-function.py` to enable use of multiple backends.

mirror show-capabilities-by-function to enable multiple backends

---

capa/features/extractors/ida/helpers.py

I ran into a situation where IDA was returning unmapped addresses when calling `idautils.DataRefsFrom`, so we need to check for this.

check for unmapped addresses when resolving data references

---

capa/ida/plugin/form.py
capa/ida/plugin/item.py
capa/ida/plugin/model.py

Adding option to show results by function, in addition to results by rule. This new option helps users quickly gain a better understanding of what functions may do depending on the rules they matched.
modeled after `scripts/show-results-by-function.py`.
results by rule (current):
results by function:

explorer: adding option to show results by function

---

capa/features/extractors/viv/insn.py

but what does this really mean? why would `getBranches` return `None`?
closes #441

viv: ignore empty branch targets

---

capa/features/extractors/viv/__init__.py
capa/features/extractors/viv/basicblock.py
capa/features/extractors/viv/insn.py
capa/features/freeze.py
capa/main.py
scripts/bulk-process.py
scripts/capa_as_library.py
scripts/lint.py
scripts/show-capabilities-by-function.py
scripts/show-features.py
scripts/vivisect-py2-vs-py3.sh
setup.py
tests/fixtures.py
tests/test_main.py
tests/test_viv_features.py

Vivisect has moved to Python3: https://github.com/vivisect/vivisect/pull/328 This PR allows to run vivisect with Python3 in capa and provides an option to select the backend (vivisect is the default but this can be easily changed). I am using the following version of vivisect (which includes fixes for some bugs I have found and I need to report to vivisect): https://github.com/Ana06/vivisect/tree/py-3
`scripts/vivisect-py2-vs-py3.sh` tests the performance of vivisect Python 2 vs 3 by counting the number
of feature of each type extracted for every binary in `tests/data`. I run it using the code in this PR with Python 2 and vivisect 0.2.0 and with Python 3 and https://github.com/Ana06/vivisect/tree/py-3. **Python3 extracted in average 101.01% percentage of the features that Python2 …

Python3 support for vivisect

---

capa/ida/plugin/form.py

addresses #463.
created a new `Settings` button that, when clicked, opens a new dialog to modify the various capa explorer settings. displayed are the current values for each setting, or blank if the setting does not have a value yet. clicking `Ok` applies the settings, clicking `Cancel` retains the previous values.

explorer: improve settings modification

---

README.md

- Add a link to the `PyPI - Python Version` badge. Otherwise it opens the image when clicking on it, which is inconsistent with the other badges. I arrived too late to point this out in: https://github.com/fireeye/capa/pull/477
- Add release badge with last release version. This may help users to realize that a new version has been released.
- Add downloads badge.
- Order labels by color.
Closes https://github.com/fireeye/capa/issues/196

doc: Improve README badges

---

setup.py

In viv-utils `getWorkspace` raises `IncompatibleVivVersion` on Python 3 when `vw.loadWorkspace(viv_file)` raises `UnicodeDecodeError`. Fixes https://github.com/fireeye/capa/issues/469

setup: bump viv-utils to 0.5.0

---

scripts/lint.py

closes #483 slightly different to #484 (I'm fine either way)
closes #482 by lint ensuring there's only CRLF line breaks and by introducing `.gitattributes` in https://github.com/fireeye/capa-rules/pull/298

ensure LF end of line

---

.github/workflows/tag.yml
doc/release.md

Add GitHub Action to tag capa-rules when releasing capa. The used tag name is the same as the one in capa. You can see in action for v1065.73.0 in Ana06/capa and Ana06/capa-rules:
- workflow run: https://github.com/Ana06/capa/runs/2095908373
- created tag: https://github.com/Ana06/capa-rules/releases
It is needed to add a `CAPA_RULES_TOKEN` in capa with the `repo` scope (I don't have permissions to add it).
Closes https://github.com/fireeye/capa/issues/458

ci: tag capa-rules on release

---

.github/workflows/tests.yml
tests/test_smda_features.py

closes #460
depends on new vivisect release to fix vtrace filepath encoding issue
what about MacOS? we can also exclude Python versions for specific OSs.
while at it, should we re-enable Python 3.6 tests?

test on Windows, Ubuntu, macOS across Python versions

---

setup.py

Fix all dependencies in setup to the currently used version to avoid
that a new release breaks capa without being noticed.
Closes https://github.com/fireeye/capa/issues/498

setup: pin dependencies

---

.github/workflows/publish.yml
.github/workflows/tests.yml
CHANGELOG.md
capa/features/__init__.py
capa/features/extractors/helpers.py
capa/features/extractors/ida/__init__.py
capa/features/extractors/ida/basicblock.py
capa/features/extractors/ida/helpers.py
capa/features/extractors/smda/__init__.py
capa/features/freeze.py
capa/helpers.py
capa/ida/helpers/__init__.py
capa/ida/plugin/README.md
capa/ida/plugin/item.py
capa/ida/plugin/proxy.py
capa/main.py
capa/render/__init__.py
capa/render/default.py
capa/render/utils.py
capa/rules.py
doc/installation.md
scripts/ci.sh
setup.py
tests/fixtures.py
tests/test_freeze.py
tests/test_helpers.py
tests/test_main.py
tests/test_smda_features.py

This PR removes Python 2 support:
- Remove py2/3 branches
- Prevent that Python is run with Python < 3.6
- Remove python 2 tests
- Test all supported Python versions (let see if 3.6 behaves)
- Update setup.py
- Document how to use env and adapt scripts/ci.sh
- Remove six
- Use python3 in shebang
- Remove rstrip("L") needed in Python 2
- remove `TypeError` check as `codecs.decode` doesn't raise that exception in Python 3
- remove code related to `cp65001` as it is recognized by Python 3
- use Python 3.6 to publish capa
For more details check the commit messages. Let me know if I am missing something!
**To be merged after the release of [capa 1.6.1](https://github.com/fireeye/capa/milestone/9).**
Closes https://github.com/fireeye/capa/issues/456

Python 3 ONLY

---

.github/workflows/tag.yml
CHANGELOG.md

GitHub displays the commit's message of the tag if no description is given, which is ugly. Use annotated tags which include a message. Use the release link as message, as this is useful information.
This is the difference between a tag created with the previous action and with the changes:

ci: add capa release link to capa-rules tag

---

CHANGELOG.md

The code of v1.6.2 is not included in the `master` branch, as it was backported to `master-py2`. But users may expect to find all releases in the CHANGELOG of the master branch. Opinions?

changelog: add v1.6.2

---

capa/ida/plugin/README.md

The Service Pack 1 for IDA 7.6 includes a bug fix that broke capa explorer. Document this as an alternative to install the patch.

doc: document IDA 7.6sp1

---

CHANGELOG.md
doc/release.md

Add missing changes to CHANGELOG. It should be up-to-date now, with the exception of the dependencies updates which I think need discussion. I am planing to send a PR with a GitHub action which automatically updates the rules. If new PRs are merge till then, we should remember to add those entries to the CHANGELOG.
Also update release checklist.
I haven't add a CHANGELOG entry for this PR, but once the new rules are automatize, I can add an entry in development mentioning this PR as well. As this point this PR just updates the CHANGELOG (although it plans for automation).

Update CHANGELOG and release

---

CHANGELOG.md
scripts/lint.py

addresses https://github.com/fireeye/capa-rules/issues/382

lint statements for single child statements

---

CHANGELOG.md
capa/features/__init__.py
capa/features/extractors/ida/file.py
capa/features/extractors/smda/file.py
capa/features/extractors/viv/file.py
capa/features/file.py
capa/rules.py
tests/fixtures.py
tests/test_rules.py
tests/test_smda_features.py

adds support for extracting `API` features at file scope to indicate statically linked routines, such as extracted via FLIRT. see idea/discussion in #567

file scope API features

---

tests/test_smda_features.py

fixes xfails since ed02088c820b95119c776ca43c51e79f22c81cac introduces new method to parametrize tests

fix smda test xfail

---

CHANGELOG.md
capa/features/__init__.py
capa/ida/plugin/model.py
capa/render/__init__.py
capa/render/vverbose.py

previously, when we evaluated a regex, we short circuited after the first match, capturing a single string with locations. but regexes can match multiple different strings, so in this PR we capture all matching strings and each of their locations. this doesn't change rule behavior (unless maybe theres a `count(regex(foo))` or something?) but it makes our feature reporting much more complete.
this requires a breaking change to the JSON document: a regex node now has a child `matches` that maps from matching string to its locations. this used to be `match` that contained just the single matching string.
our renders and IDA plugin have been updated.
closes #159

json: capture all strings matching regex

---

CHANGELOG.md
capa/render/__init__.py
capa/render/default.py
capa/render/utils.py
capa/render/vverbose.py
capa/rules.py
tests/test_main.py
tests/test_render.py
tests/test_rules.py

Add ATT&CK like MBC (#576)
#526

parse att&ck for output doc

---

.github/workflows/tests.yml
CHANGELOG.md

The sync GH action in capa-rules relies on a single `- *$` in the CHANGELOG file. Check in the tests that this is the case to avoid that it is removed.
This happened in https://github.com/fireeye/capa/pull/591, which caused that the new rules in https://github.com/fireeye/capa-rules/pull/400 were not added to the CHANGELOG.
There are probably better alternatives to update the CHANGELOG than looking for `- *$`. Any ideas of how to do this in a robuster way that doesn't need linting?  🤔 Otherwise this is an easy solution which may be good enough.

ci: lint CHANGELOG

---

.github/workflows/changelog.yml

Use [Ana06/get-changed-files@v1.2](https://github.com/Ana06/get-changed-files/releases/tag/v1.2) which removes the _head commit is ahead of the base commit_ check. This made the action failed in not up-to-date branches (in which rebasing is needed).
I think we should update capa-rules and capa-testfiles as well.
It supersedes https://github.com/fireeye/capa/pull/599

Use Ana06/get-changed-files@v1.2

---

CHANGELOG.md
capa/features/insn.py

closes #619 by correctly rendering negative numbers and offsets.
this is a breaking change because our JSON document currently contains incorrectly formatted values. probably noone relies on this, though.

correctly render negative numbers and offsets

---

CHANGELOG.md
capa/features/freeze.py
capa/main.py
doc/usage.md
scripts/bulk-process.py
scripts/capa_as_library.py
scripts/lint.py
scripts/show-capabilities-by-function.py
tests/fixtures.py

by default, don't create .viv files, unless env var `CAPA_SAVE_WORKSPACE` is set.
closes #507

disable viv creation by default

---

CHANGELOG.md
capa/ida/plugin/README.md
capa/ida/plugin/__init__.py
capa/ida/plugin/form.py

I would like to load capa explorer with an script and that it runs the
analysis without needing extra clicks. Introduce an analyze option for
this.
Loading capa explorer from the UI or with Alt+F5 behaves as before. The
following command as well:
```
ida_loader.load_and_run_plugin("capa_explorer", 0)
```
But the following command automatically runs the analysis without extra
clicks:
```
ida_loader.load_and_run_plugin("capa_explorer", 1)
```
Example of where I am using this:
https://github.com/Ana06/idapython/blob/master/idapythonrc.py#L22
Closes https://github.com/fireeye/capa/issues/546
- Breaking changes (fix or feature that would cause existing functionality to not work …

explorer: add analyze option

---

CHANGELOG.md
capa/ida/plugin/view.py

closes #544.
allow user to add specified number of bytes when adding a `Bytes` feature in the rule generator. adds `Add n bytes...` option to context menu for `Bytes` features.

add option to select specificed byte count for bytes feature

---

CHANGELOG.md
capa/ida/plugin/form.py
capa/ida/plugin/view.py

closes #473.
This update adds an option to limit features displayed in the `Features` pane to the currently selected address in the disassembly view. Opting for simplest implementation here to balance ROI.

add option to limit features to currently selected disassembly address

---

CHANGELOG.md
capa/features/extractors/viv/file.py
capa/features/extractors/viv/insn.py
capa/main.py

Add initial elf files support

---

.github/mypy/mypy.ini
CHANGELOG.md
scripts/lint.py

a number of semi-related enhancements to the linter:
- add typing
- add progress bar
- add (in-memory) cache of analysis results per-path 
- don't display "find examples" if its the only violation for a nursery rule
all together, this should make the output much more readable while also being more performant (via the cache).

linter enhancements

---

.github/mypy/mypy.ini
CHANGELOG.md
capa/features/common.py
capa/features/extractors/base_extractor.py
capa/features/extractors/common.py
capa/features/extractors/elf.py
capa/features/extractors/elffile.py
capa/features/extractors/pefile.py
capa/features/extractors/viv/file.py
capa/main.py
capa/rules.py
setup.py

Add a basic ELF feature extractor similar to the pefile one in support of #699.

add light weight ElfFeatureExtractor

---

CHANGELOG.md
capa/engine.py
capa/features/common.py

```
common -> engine -> rules -> insn -> common
```
Move `Result` from `capa.engine` to `capa.common`.

fix circular import freeze

---

CHANGELOG.md
capa/optimizer.py
capa/rules.py
tests/test_optimizer.py

please review and merge #828 and #827 before this.
This PR adds a rule optimizer that re-orders the nodes in the rule logic tree to try simpler/faster cases before complex cases. For example, it prefers OS checks before mnemonic checks before regex checks.
In practice, this seems to make a small, but measurable difference in execution time:
| label                                | count(evaluations)   | avg(time)   | min(time)   | max(time)   |
|--------------------------------------|----------------------|-------------|-------------|-------------|
| 18c30e4 base | 108,121              | 0.38s       | 0.34s       | 0.55s       |
| a6e2cfc base short circuiting | 69,401               | 0.23s       | 0.22s       | 0.26s       |
| 152d0f3 de-optimizer | 78,900               | 0.28s       | …

perf: add query optimizer

---

.github/workflows/tests.yml
CHANGELOG.md
setup.py

viv-utils v0.6.9 depends on python-flirt v0.7.0 that adds:
- python 3.10 builds
- aarch64 and armv7 builds
- macOS universal2 and x86_64 builds
closes #816 
closes #683

setup: bump viv-utils to v0.6.9

---

capa/helpers.py
capa/rules.py

This PR addresses issue #835, and should help with exhaustiveness checking for types. Running `mypy capa/rules.py` showed no errors before I made these changes.
Output of `mypy capa/rules.py` after change:
```
capa/rules.py:1095: error: Argument 1 to "assert_never" has incompatible type "Statement"; expected "NoReturn"
capa/rules.py:1200: error: Argument 1 to "assert_never" has incompatible type "Scope"; expected "NoReturn"
Found 2 errors in 1 file (checked 1 source file)
```

types: Add assert_never for exhaustivenes checking with mypy

---

CHANGELOG.md
capa/render/utils.py
capa/rules.py

closes #841 
see https://github.com/mandiant/capa-rules/pull/515
note: none of the `maec/*` fields is displayed and the so tagged rules are not shown as capability rules.

support maec/malware-family meta

---

CHANGELOG.md
capa/ida/helpers.py
capa/ida/plugin/README.md

fixes #845. pinning supported IDA version to IDA >= 7.4 and IDA < 8.0.

capa explorer: updating supported IDA versions

---

CHANGELOG.md
capa/features/extractors/smda/insn.py
scripts/show-features.py
tests/fixtures.py

SMDA extractor is extracting negative Number features as described in #430.
This is not compliant with the rule format described in capa documentation:
> Note that capa treats all numbers as unsigned values. A negative number is not a valid feature value. To match a negative number you may specify its two's complement representation. For example, 0xFFFFFFF0 (-2) in a 32-bit file.
https://github.com/fireeye/capa-rules/blob/master/doc/format.md#number
This PR adds the following fixtures:
- number(0x0): to check feature extraction for null number
- number(0xFFFFFFFF): to check feature extraction for -1 number
- number(0xFFFFFFF0): to check feature extraction for another negative number (-0x10 in this case)
The function `extract_insn_number_features` now converts the parsed smda number …

smda: fix negative number extraction

---

capa/features/extractors/ida/global_.py

```
if info.procName == "metapc" and info.is_64bit():
Please use "procname" instead of "procName" ("procName" is kept for backward-compatibility, and will be removed soon.)
```

Fix deprication warning from IDA

---

CHANGELOG.md
capa/features/extractors/smda/insn.py
capa/features/extractors/viv/insn.py
tests/fixtures.py

This PR adds a new characteristic feature named `call $+5` with the support of smda and vivisect backend.
I did not update the IDA extractor because I don't have a IDA pro license.
I see that the characteristic features are defined inside [format.md](https://github.com/mandiant/capa-rules/blob/master/doc/format.md#characteristic). What's the workflow for the documentation update? Should I wait for this to be merged?
Closes #366:
> ### Summary
> Add (one-off) feature to match on `call $+5`; often used in shellcode or for obfuscation.
> 
> ### Motivation
> Help to detect shellcode and anti-disassembly techniques.

Add characteristic "call $+5" feature with support for vivisect and smda

---

CHANGELOG.md
setup.py

Remove requirement for separate typing package; typing is in the Python stdlib from 3.5, and we require >= 3.6. From 3.7, installing the typing package causes import failures.
See [here](https://github.com/python/typing/issues/573) for numerous examples of the `typing` package causing import exceptions with Python >= 3.7.

Don't require typing package; it's in the stdlib now

---

.github/workflows/build.yml

The Windows 2016 runner image will be removed from GitHub-hosted runners
on March 15, 2022:
https://github.blog/changelog/2021-10-19-github-actions-the-windows-2016-runner-image-will-be-removed-from-github-hosted-runners-on-march-15-2022

remove windows-2016

---

CHANGELOG.md
capa/features/extractors/ida/file.py

improves file format extraction - only raise `NotImplementedError` if file format is not one of PE, ELF, or binary.

fixes #911

---

capa/render/verbose.py

render: meta: display rule paths on separate lines

---

capa/render/vverbose.py

vverbose: don't show examples in output

---

.github/workflows/tests.yml
capa/features/extractors/dnfile_.py
tests/fixtures.py
tests/test_dotnet_features.py

Dotnet mixed mode detect

---

CHANGELOG.md
capa/features/extractors/ida/helpers.py
capa/features/extractors/ida/insn.py
capa/features/extractors/smda/insn.py
capa/features/extractors/viv/insn.py
capa/features/insn.py
tests/fixtures.py
tests/test_smda_features.py

extract extra offset/number features

---

.github/workflows/tests.yml
capa/features/address.py
capa/features/extractors/dnfile/extractor.py
capa/features/extractors/dnfile/insn.py
capa/features/extractors/elf.py
capa/features/extractors/ida/basicblock.py
capa/features/extractors/ida/extractor.py
capa/features/extractors/ida/file.py
capa/features/extractors/ida/function.py
capa/features/extractors/ida/global_.py
capa/features/extractors/ida/helpers.py
capa/features/extractors/ida/insn.py
capa/features/extractors/smda/extractor.py
capa/features/extractors/smda/insn.py
capa/features/extractors/viv/extractor.py
capa/features/extractors/viv/function.py
capa/features/extractors/viv/indirect_calls.py
capa/features/extractors/viv/insn.py
capa/ida/plugin/__init__.py
capa/ida/plugin/form.py
capa/ida/plugin/item.py
capa/ida/plugin/model.py
capa/main.py
scripts/show-features.py
tests/fixtures.py

and various other fixes
test in IDA pass, outstanding test fails are due to freeze, JSON, and dotnet issues
```
OK   mimikatz-function=0x40E5C2-basic block-7
OK   mimikatz-function=0x4702FD-characteristic(calls from)-0
OK   mimikatz-function=0x40E5C2-characteristic(calls from)-3
OK   mimikatz-function=0x4556E5-characteristic(calls to)-0
OK   mimikatz-function=0x40B1F1-characteristic(calls to)-3
SKIP 3b13b...-function=0x10006860-characteristic(nzxor)-True
SKIP 64d9f-function=0x10001510,bb=0x100015B0-offset(0x4000)-True
SKIP 7351f.elf-file-os(linux)-True
SKIP 7351f.elf-file-os(windows)-False
SKIP 7351f.elf-file-format(elf)-True
SKIP 7351f.elf-file-format(pe)-False
SKIP 7351f.elf-file-arch(i386)-False
SKIP 7351f.elf-file-arch(amd64)-True
SKIP …
```

feat: add IDA handles and type annotations

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

github codespaces is a cloud development environment that uses VS Code and docker images. more details here: https://github.com/features/codespaces (sign up for the beta!).
here you can see me working on capa within a codespace:
this PR adds a basic codespaces configuration to capa so that its easy for people to open and contribute to the project via codespaces.
pro:
- easy to add (easy to remove)
- some people might use it
- we can try new tech
cons:
- more noise in the top directory
- codespaces may not survive for years (so we may have to remove the config eventually)

add Github Codespaces config

---

capa/ida/plugin/form.py
capa/main.py

When using a git repo version of `capa-rules`, `capa` iterates through `.git` looking for rules (which obviously doesn't have any) and emits some warnings that bloat the log. This PR filters out `/.git` when crawling the fs looking for rules.
```
WARNING:capa.ida.plugin.form:skipping non-.yml file: description
WARNING:capa.ida.plugin.form:skipping non-.yml file: config
WARNING:capa.ida.plugin.form:skipping non-.yml file: index
WARNING:capa.ida.plugin.form:skipping non-.yml file: HEAD
WARNING:capa.ida.plugin.form:skipping non-.yml file: packed-refs
WARNING:capa.ida.plugin.form:skipping non-.yml file: HEAD
WARNING:capa.ida.plugin.form:skipping non-.yml file: master
WARNING:capa.ida.plugin.form:skipping non-.yml file: HEAD
WARNING:capa.ida.plugin.form:skipping non-.yml file: …
```

ignore .git/ when loading capa rules

---

.github/workflows/tag.yml
CHANGELOG.md
capa/ida/plugin/form.py
capa/main.py
capa/version.py
doc/installation.md
doc/release.md
doc/rules.md

add documentation to the readmes explaining https://github.com/mandiant/capa-rules/issues/556
closes #764
closes #529

document rule branches

---

.github/workflows/build.yml
.github/workflows/tests.yml

Not sure if this breaks things for older macOS versions. In that case we can revert to `macos-10.15` which will still be supported.
closes #793

ci: use macos-11

---

CHANGELOG.md
capa/render/vverbose.py

also, display `number` features as hex.

render: display number zero vverbose

---

CHANGELOG.md
scripts/lint.py

addresses #1138
see https://github.com/mandiant/capa-rules/issues/606 for affected rules (41)

linter: use pydantic to validate rule metadata

---

capa/render/result_document.py

This fixes an issue where a ValidationError is raised when `argv` is not in the passed metadata and set to None in the function from_capa.
Example Exception 
```
...
File "../capa/render/result_document.py", line 88, in from_capa
return cls(
File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Metadata
argv
none is not an allowed value (type=type_error.none.not_allowed)
```
Current definition expects a Tuple
https://github.com/mandiant/capa/blob/master/capa/render/result_document.py#L78
When `argv` is not within the passed fields, the function will set the value to None 
https://github.com/mandiant/capa/blob/master/capa/render/result_document.py#L87

Add Optional attribute to argv property in Metadata model. 

---

capa/render/vverbose.py

Small fix to correct a typo in the vverbose render.

Fix maec.malware_category_ov typo in vverbose render

---

CHANGELOG.md
capa/ida/plugin/item.py
capa/ida/plugin/model.py

fix: display instruction items

---

CHANGELOG.md
capa/rules.py
tests/test_main.py

Avoid to load and match to then fail on invalid rule meta when rendering.

feat: verify rule metadata format on load

---

CHANGELOG.md
capa/features/extractors/dnfile/helpers.py
capa/features/extractors/dnfile/insn.py
tests/fixtures.py

Objects created via the `newobj` instruction are emitted as `api` features using the hard-coded method name `ctor` e.g. `System.Threading.Mutex::ctor`. This addition enables users to write rules specific to objects created at runtime in .NET.
see https://github.com/mandiant/capa-rules/pull/626 for example rules.
closes #1150

dotnet: emit features from newobj instruction

---

CHANGELOG.md
capa/features/extractors/dnfile/extractor.py
capa/features/extractors/dnfile/function.py
tests/fixtures.py

closes #1096 
We calculate calls to/from while extracting `MethodDef` methods enabling matching for the following characteristics:
```yaml
- characteristic: calls to
- characteristic: calls from
- characteristic: recursive call
```

dotnet: emit calls to/from MethodDef methods

---

CHANGELOG.md
capa/features/extractors/dnfile/extractor.py
capa/features/extractors/dnfile/insn.py
tests/fixtures.py

dotnet: emit namespace/class features for ldvirtftn/ldftn instructions

---

CHANGELOG.md
capa/features/extractors/dnfile/extractor.py
capa/features/extractors/dnfile/helpers.py
capa/features/extractors/dnfile/insn.py
capa/features/extractors/dnfile/types.py
tests/fixtures.py

closes #982 
cache .NET token lookup tables per extractor instead of per .NET method.

dotnet: emit namespace/class features for type references

---

CHANGELOG.md
capa/features/extractors/ida/helpers.py
capa/features/extractors/ida/insn.py

fixes #1243 
see #1243 for discussion on the fix.

explorer: assume 32-bit displacement for offsets

---

CHANGELOG.md
capa/ida/plugin/README.md
capa/ida/plugin/form.py

closes #1244 . Opted to generate ruleset URL using `capa.version.__version__` instead of including capa version in the explorer UI. I believe this will make it easier for users to locate the correct ruleset for their capa/explorer installation.

explorer: improve ruleset error messaging and documentation

---

CHANGELOG.md
capa/ida/plugin/cache.py
capa/ida/plugin/error.py
capa/ida/plugin/extractor.py
capa/ida/plugin/form.py
capa/ida/plugin/view.py

explorer: overhaul rule generator caching and matching

---

CHANGELOG.md
capa/ida/plugin/form.py

Closes #1261
Improved exception handling to prevent IDA from locking up if certain errors occur during execution. User is presented with a dialog indicating an error occurred and they should see the output window for more details.

explorer: improve exception handling

---

capa/main.py

noticed in https://github.com/mandiant/capa-rules/actions/runs/3839982465/jobs/6538477340
prior diff

fix logic error from smda backend removal

---

CHANGELOG.md
capa/render/utils.py
capa/render/vverbose.py

only show first lib match to reduce vverbose output noise

---

CHANGELOG.md
capa/features/common.py
capa/features/extractors/common.py

closes #1267 
i wasnt able to reproduce the issue as described, but i can see in the code how this would happen, so @mr-tz please confirm this fix

features: string: better __str__ embedded whitespace

---

setup.py

Reverts mandiant/capa#1275
networkx >2.5.1 does not support python 3.7 (which we do), so cannot upgrade now.

Revert "build(deps): bump networkx from 2.5.1 to 3.0"

---

CHANGELOG.md
capa/features/extractors/viv/insn.py
tests/fixtures.py

closes #1271
try to detect the case in which viv incorrectly returned a substring length and truncate the returned data appropriately. i think this will work better for ASCII than for UTF16 because we can better guess about embedded NULL bytes.

viv: insn: string: handle viv bug around substrings

---

CHANGELOG.md
capa/features/extractors/dnfile/extractor.py
capa/features/extractors/ida/extractor.py
capa/features/extractors/viv/extractor.py
capa/helpers.py
capa/main.py
scripts/lint.py
scripts/show-capabilities-by-function.py
tests/fixtures.py

closes #1258 
related to #1187 
tests succeed in IDA
```
--------------------------------------------------------------------------------
OK   mimikatz-function=0x40E5C2-basic block-7
OK   mimikatz-function=0x4702FD-characteristic(calls from)-0
OK   mimikatz-function=0x40E5C2-characteristic(calls from)-3
OK   mimikatz-function=0x4556E5-characteristic(calls to)-0
OK   mimikatz-function=0x40B1F1-characteristic(calls to)-3
...
OK   mimikatz-file-string(SCardControl)-True
OK   mimikatz-file-string(SCardTransmit)-True
OK   mimikatz-file-string(ACR  > )-True
OK   mimikatz-file-string(nope)-False
OK   mimikatz-file-section(.text)-True
OK   mimikatz-file-section(.nope)-False
OK   mimikatz-file-import(advapi32.CryptSetHashParam)-True
OK   mimikatz-file-import(CryptSetHashParam)-True
OK …
```

add format to global features and code refactors

---

CHANGELOG.md
capa/features/extractors/dnfile/insn.py
capa/features/extractors/ida/helpers.py
capa/features/extractors/ida/insn.py
capa/features/extractors/viv/insn.py

noticed via test fails in weekly thorough lint: https://github.com/mandiant/capa-rules/actions/runs/4035045319/jobs/6936699063
Added wrongly in ca9c9400a5f552463733608380be3236bad51e09 and discovered similar bugs in related code.
closes #1293

Fix string length >= 4 and remove bytes/string overlaps

---

CHANGELOG.md
capa/ida/plugin/form.py
capa/ida/plugin/model.py
capa/main.py

- fixes 2 recently introduced unbounded exceptions
- fixes rendering bug found in "limit results by function"

explorer: fix multiple bugs

---

capa/features/freeze/__init__.py
capa/render/verbose.py

improve the type annotations for the Address value property.

freeze: better type annotations for Address value

---

CHANGELOG.md
capa/features/extractors/ida/insn.py
capa/features/extractors/viv/insn.py
tests/fixtures.py

This PR fixes some unit tests that wrongly treat strings features as bytes features. It also fixes a bug in the IDA extractor that causes the old unit test to pass.
closes https://github.com/mandiant/capa/issues/1336 https://github.com/mandiant/capa/issues/1327
ref: #1338

Fix byte/string extraction and unit tests

---

CHANGELOG.md
capa/features/extractors/ida/file.py

explorer: improve embedded PE detection

---

capa/features/extractors/binja/file.py
capa/features/extractors/binja/find_binja_api.py
capa/features/insn.py
capa/main.py

this is the last of the candidate format strings that can be reasonably translated into f-strings.
closes #600

use f-strings as appropriate

---

CHANGELOG.md
capa/features/extractors/ida/helpers.py

ELF Imports including dynsym as a library name is not useful and may cause conflicts with rules or users of capa as a python library. This removes the library name for elf binaries.
This change was discussed with @mike-hunhoff

Remove dynsym library name for ELF imports

---

capa/features/extractors/elf.py
tests/test_os_detection.py

this closes  #1403 
__detect_elf_os()__ now parses the ELF file's symbols' names (if present) and attempts to guess the target OS.

ELF OS detection: add support for guessing that's based on .symtab entries

---

.github/workflows/build.yml
.github/workflows/tests.yml
capa/features/extractors/elf.py
capa/features/extractors/ida/helpers.py
capa/main.py
capa/render/result_document.py
tests/fixtures.py
tests/test_main.py
tests/test_result_document.py

fixes:
- mypy v1.1.1 for newly merged code
- more thorough deserialization of result document, as identified by mypy
- elf typing
- elf test case failures

more mypy v1.1.1 fixes

---

capa/main.py

Give the user an instruction link to install signatures if they installed Capa via pip
related #682

fix: Warning user to install signatures

---

CHANGELOG.md
capa/features/extractors/binja/function.py

Check if caller.llil is None before accessing its properties

---

CHANGELOG.md
capa/features/extractors/elf.py

This fixes symtab's struct.unpack() format for 64-bit ELF binaries. The previous unpacking was off by one byte for the fields: shndx, value and size.
This also adds a safeguard against binaries that — for some reason — might have symtab with a null entry size.

SymTab _parse(): Bugfixes for the struct unpacking and for handling symtabs with a null entry size

---

CHANGELOG.md
capa/features/extractors/binja/find_binja_api.py

This fixes a minor issue that the binja installation path detection does not work with Python 3.11. Close https://github.com/mandiant/capa/issues/1430

Fix BN installation path detection does not work with Python 3.11

---

capa/features/extractors/elf.py

Added more try/excepts around the parsing code in detect_elf_os
Closes #1458

Added try/except blocks to detect_elf_os in elf.py for improved ELF parsing and OS detection

---

CHANGELOG.md
capa/main.py

Redirecting logging message to tqdm for improved functionality while debugging
Closes #1492 
Resolves https://github.com/mandiant/capa/pull/1481#issuecomment-1549580087

Add logging redirect to capa main

---

CHANGELOG.md
capa/ida/helpers.py
capa/ida/plugin/form.py
capa/main.py
capa/render/result_document.py
scripts/bulk-process.py
scripts/capa_as_library.py
scripts/show-capabilities-by-function.py
tests/test_result_document.py

Closes Issue #1411 
Closes PR #1444

Update Metadata type in capa main

---

CHANGELOG.md
capa/features/extractors/binja/basicblock.py
tests/test_binja_features.py

This PR updates the BN stack string detection code, leveraging the constant outlining feature introduced in BN 3.5. 
The constant outlining, in short, detects memory writes to the stack and convert them into a more readable `strcpy`, e.g., 
```
13 @ 00455755  __builtin_strncpy(dest: &var_10c_112, src: "AAAA", n: 4)
```
instead of 
```
00455755  mov     dword [ebp-0x108 {var_10c}], 0x41414141
0045575f  mov     dword [ebp-0x104 {var_108}], ebx  {0x0}
```
The constant outlining feature was previously causing the capa CI to fail, since the old extractor code is unaware of the new pattern. 
This PR keeps the old way of doing stack string detection and falls back to it if the new feature is unavailable. This ensures capa works properly on an older version of BN. 
This PR fixes …

Update the stack string detection with BN's builtin outlining of constant expressionss

---

capa/features/extractors/base_extractor.py

This is the parent branch of the cape-dynamic-extractor and cuckoo-dynamic extractor; The two will ensue later on. It defined the interface that all dynamic sandbox-based feature extractors should implement.

add a Dynamic extractor interface

---

.github/mypy/mypy.ini
CHANGELOG.md
tests/test_ida_features.py

make it easier to run the IDA feature tests using the existing tests, such as from the commandline via idat:
closes #1364

tests: refine the IDA test runner

---

CHANGELOG.md
scripts/import-to-ida.py

closes #1584 
these changes will work with JSON reports created from master/v6 but not backwards on v5. there's a script that works on v5 here: https://github.com/mandiant/capa/blob/19a5ef8/scripts/import-to-ida.py

fix import-to-ida due to changes in the result document format in v5

---

CHANGELOG.md
capa/main.py
capa/render/default.py
setup.py

closes #1586 
current:
proposed:

use fancy box drawing characters for default output

---

CHANGELOG.md
capa/main.py

main: log time taken to analyze each function

---

.github/workflows/build.yml
.github/workflows/changelog.yml
.github/workflows/publish.yml
.github/workflows/tag.yml
.github/workflows/tests.yml

https://github.com/mandiant/capa/security/code-scanning/30
https://github.com/mandiant/capa/security/code-scanning/29
https://github.com/mandiant/capa/security/code-scanning/27

ci: set top level permissions to satisfy code scanning

---

CHANGELOG.md
capa/main.py

main: don't show spinner when debug messages are emitted

---

CHANGELOG.md
capa/version.py

ref #1622 
note this is a pre-release v6.0.0a1 so that i can verify the release gets published correctly.

prep v6.0.0a1

---

CHANGELOG.md
capa/features/address.py
capa/features/extractors/base_extractor.py
capa/features/extractors/cape/call.py
capa/features/extractors/cape/extractor.py
capa/features/extractors/cape/thread.py
capa/features/extractors/null.py
capa/features/freeze/__init__.py
capa/main.py
capa/render/verbose.py
capa/rules/__init__.py
scripts/show-features.py
tests/fixtures.py
tests/test_main.py
tests/test_rules.py

This PR is for adding the call scope.
For the time being, the call scope supports only the features: `API`, `Number`, and `String`.
Also, I have also modified the dynamic-related addresses to include a reference to each one's parent scope/address. This is in order to avoid the mixing of extracted features. For example, two api calls with the same id's, two threads with the same ids, and two processes with the same pid.

Add a call scope

---

capa/features/extractors/ghidra/helpers.py
capa/features/extractors/ghidra/insn.py

---
Implements #1511 : Instruction Feature Extraction

Ghidra insn features

---

CHANGELOG.md
capa/ida/plugin/form.py

closes #1661 
`pathlib.Path` considers an empty string equivalent to `.` which breaks the logic used to ensure a user has selected a valid capa rules path. This bug was introduced in https://github.com/mandiant/capa/commit/edeb458b337246c22945bb9484dde211b2d6846f.

explorer: fix unhandled exception when resolving rule path

---

CHANGELOG.md
capa/features/extractors/elf.py
tests/fixtures.py
tests/test_os_detection.py

closes #1705
test file: https://github.com/mandiant/capa-testfiles/pull/212

elf: detect Android OS via note and dependencies

---

CHANGELOG.md
capa/features/extractors/elf.py
capa/features/extractors/viv/function.py
capa/features/extractors/viv/insn.py

closes #1704 
also cleans up naming and type hints

elf: fix parsing of symtab from viv data

---

capa/features/address.py
capa/features/extractors/cape/call.py
capa/features/freeze/__init__.py
capa/render/verbose.py
scripts/show-features.py
tests/fixtures.py
tests/test_extractor_hashing.py
tests/test_main.py

please review and merge #1709 first
remove the return address concept, since it wasn't really used by any scripts or capa analysis. this reduces the amount of code to maintain.
i think the intent was to potentially assist analysts that encounter an interesting API call in mapping that back to the input binary. we can do this by recording more details, including return address, about API calls in the "layout", and then referencing this during rendering.

remove dynamic return address concept

---

CHANGELOG.md
capa/features/freeze/__init__.py
capa/ida/helpers.py
capa/main.py
capa/render/result_document.py
scripts/import-to-ida.py
scripts/proto-from-results.py
tests/fixtures.py
tests/test_ida_features.py
tests/test_result_document.py

fix deprecation warnings

---

capa/features/extractors/ghidra/helpers.py

properly set bounds for find_byte_sequence

---

CHANGELOG.md
capa/features/extractors/ghidra/file.py
capa/features/extractors/ghidra/helpers.py
capa/ghidra/helpers.py

Apparently `int.to_bytes` is horribly inefficient.
Before changes
```
7   13.215    1.888   13.620    1.946 helpers.py:60(get_block_bytes)
```
After changes:
```
7    0.000    0.000    0.044    0.006 helpers.py:58(get_block_bytes)
```
This PR also contains small API changes to the Ghidra helper functions.

fix ints_to_bytes performance

---

capa/features/extractors/base_extractor.py
capa/features/extractors/binja/extractor.py
capa/features/extractors/cape/extractor.py
capa/features/extractors/dnfile/extractor.py
capa/features/extractors/dnfile_.py
capa/features/extractors/dotnetfile.py
capa/features/extractors/ida/extractor.py
capa/features/extractors/null.py
capa/features/extractors/pefile.py
capa/features/extractors/viv/extractor.py

This PR moves the extractor's sample hashes attribute and method to the base class.

Modify sample hashes

---

CHANGELOG.md
capa/version.py

- capa https://github.com/mandiant/capa/compare/v6.0.0...master
- capa-rules https://github.com/mandiant/capa-rules/compare/v6.0.0...master
```
-
- [capa <release>...master](https://github.com/mandiant/capa/compare/v6.1.0...master)
- [capa-rules <release>...master](https://github.com/mandiant/capa-rules/compare/v6.1.0...master)
```

version: v6.1.0

---

CHANGELOG.md
capa/ida/plugin/model.py
capa/main.py
capa/render/verbose.py
capa/render/vverbose.py
capa/rules/__init__.py
scripts/show-capabilities-by-function.py
tests/_test_proto.py
tests/test_rules.py

this PR updates code across capa to prefer to use `Scope.FOO` instead of `FOO_SCOPE`. before, we had two ways of doing things. now we have one. preferring to use the enum is better because it lets type checkers reason about the set of values, rather than arbitrary strings.

rules: use Scope enum instead of constants

---

capa/exceptions.py
capa/features/extractors/cape/call.py
capa/features/extractors/cape/extractor.py
capa/features/extractors/cape/models.py
capa/features/extractors/cape/thread.py
capa/helpers.py
capa/main.py
scripts/lint.py
scripts/show-features.py

addresses various issues encountered during testing

improve and fix various dynamic parts

---

capa/features/extractors/common.py
capa/helpers.py
doc/installation.md
tests/test_main.py

identify potential JSON object data start

---

CHANGELOG.md
capa/features/extractors/null.py
capa/features/freeze/__init__.py
tests/test_freeze_dynamic.py

This PR updates the freeze implementation that supports dynamic analysis. The primary change is to keep the file format  similar as possible to v1 and v2: the magic header, compression, and json format remain the same; the version is bumped to 3; and the json document must contain a key "flavor" that specifies static/dynamic.
The upside is that the code/format remains more similar to before (though, I'm not sure anyone actually uses this format or cares about its compatibility). A downside is that there's an additional json decoding pass used to extract version/flavor, but I dont think this should be too expensive.
Added tests that demonstrate the new format works as expected (and fixed a couple bugs).
ref #1697

update freeze for dynamic

---

CHANGELOG.md
capa/features/extractors/binja/file.py
capa/features/extractors/cape/file.py
capa/features/extractors/cape/thread.py
capa/features/extractors/dotnetfile.py
capa/features/extractors/ghidra/file.py
capa/features/extractors/ghidra/helpers.py
capa/features/extractors/helpers.py
capa/features/extractors/ida/file.py
capa/features/extractors/pefile.py
capa/features/extractors/viv/file.py
capa/rules/__init__.py
tests/fixtures.py
tests/test_rules.py

Ignore DLL names for API features

---

capa/features/extractors/cape/models.py
tests/test_cape_model.py

Before strings would always be parsed as hex numbers

fix parsing base 10/16

---

capa/features/extractors/common.py

fix whitespace removal in format check

---

pyproject.toml

Regular Expression Denial of Service (ReDoS)
MEDIUM SEVERITY
Package Manager: pip
Vulnerable module: pydantic
Remediation
Upgrade pydantic to version 1.10.13, 2.4.0 or higher.

fix pydantic vuln (ReDoS)

---

capa/features/extractors/cape/extractor.py
capa/main.py

Global features were not properly extracted before so no rules with os, format, arch would hit in dynamic flavor.
Also addressing the potential duplicate output for limitation hits.

Fix global features and display

---

.github/workflows/build.yml

add build for Python 3.11 for linux

---

capa/main.py

dynamic: fix UnboundLocalError exception

---

capa/features/extractors/helpers.py
capa/rules/__init__.py
tests/test_helpers.py

supports https://github.com/mandiant/capa-rules/issues/855 and fixes symbol generation code (noted for rule `enumerate domain computers via LDAP`)

fix symbol generation, ordinals

---

capa/rules/__init__.py
tests/test_rules.py

capa v7 ignores the DLL portion of API features. Unfortunately the logic that implements this created a subtle bug that breaks matching for `.NET` `api` features e.g. `System.Convert::FromBase64String`. This PR updates the `trim_dll_part` function to fix the bug.

fix: do not trim api names that include ::

---

CHANGELOG.md
capa/features/extractors/elf.py
capa/render/default.py

addressing an OS detection miss on a private sample

elf: detect linux via GCC .ident directives

---

.github/workflows/build.yml

This PR enables tracebacks on PR build attempts. Currently, users see a rather unhelpful message if their PR build attempts fail. This would enable users to see full tracebacks.

Enable tracebacks on PR build attempts

---

CHANGELOG.md
capa/features/extractors/elf.py

developed via access to a private sample.

more ELF OS detection techniques

---

CHANGELOG.md
capa/features/extractors/elf.py
capa/loader.py
capa/main.py
capa/rules/__init__.py

closes #1810 
This PR moves the import of some dependencies closer to where they are used. This enables some capa users to avoid installing all dependencies (such as vivisect) while still being able to invoke some functionality.

defer loading of some dependencies

---

.github/workflows/build.yml
.github/workflows/publish.yml
.github/workflows/scorecard.yml
.github/workflows/tag.yml
.github/workflows/tests.yml
CHANGELOG.md

update github workflows to use latest version of checkout and setup-python

---

README.md

Since mandiant/capa-rules#882, the README badge in capa is not updated anymore via commits anymore, but in a gist.

[CI] Use badge in gist for rules number in README

---

CHANGELOG.md

I didn't originally add the gist badge to the CHANGELOG in #2001, but I am thinking now that it may be a good idea to track it in order to keep our detailed CHANGELOG up-to-date. 😉

[changelog] Add gist badge

---

.github/workflows/changelog.yml
CHANGELOG.md

Sending a PR review with a message about the CHANGELOG needing to be updated has been broken since July, where the permissions were changed in https://github.com/mandiant/capa/pull/1635. Update also to the new version of `Ana06/automatic-pull-request-review` using Node 20.

Fix CHANGELOG PR review & update Ana06/automatic-pull-request-review

---

.github/workflows/changelog.yml
.github/workflows/scorecard.yml
.github/workflows/tag.yml
.github/workflows/tests.yml
CHANGELOG.md

Update actions using a deprecated version of Node: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20

[CI] Update GitHub actions to versions using Node 20

---

.github/workflows/tests.yml
CHANGELOG.md

Updated ci workflow to reflect latest [ghidrathon release](https://github.com/mandiant/Ghidrathon/releases/tag/v4.0.0) and bumped up ghidra and jep versions. This PR closes issue #1976. CHANGELOG updated.
@mike-hunhoff requesting review, updated with comments. Apologies for new PR, I had conflicts I couldn't resolve on previous PR.

Update github ci workflow to reflect new ghidrathon release installation

---

capa/ida/plugin/view.py
capa/rules/__init__.py
scripts/lint.py
tests/test_rules.py

closes #1747 
handles circular dependencies in `filter_rules_by_meta` and `get_rules_and_dependencies`

Handles circular dependencies while getting rules and dependencies

---

CHANGELOG.md
capa/features/extractors/ida/helpers.py

This change closes #1606 by replacing the deprecated IDA API `find_binary` with `bin_search`.

ida-explorer: replace deprecated IDA API find_binary with bin_search

---

CHANGELOG.md
capa/features/extractors/dotnetfile.py

Changed format order for .NET files 
closes #2022

[ENH] Refactor format in `capa/features/extractors/dotnetfile.py`

---

CHANGELOG.md
capa/features/extractors/binja/basicblock.py
capa/features/extractors/binja/file.py
tests/test_binja_features.py

Close https://github.com/mandiant/capa/issues/2016
The PR contains:
1. The binja version check update in https://github.com/mandiant/capa/commit/bf4695c6bfdd9cffbaf45b2d1912b94cc8cbab28. Which is a standard operation after we release a new stable
2. Fix the stack string detection code after 4.0 (https://github.com/mandiant/capa/commit/58e4a30156668bbd280efbb5295ccb840aebe080), and also simplify it a bit
3. Added support for forwarded export in the binja feature extractor, and enabled the relevant unit tests. https://github.com/mandiant/capa/commit/92cfc0caa7131e941f7f4ce110254c28e6d8630b. This is a bit funny, that I fixed a relevant bug on the binja end that blocks it, and prematurely asked Willi to close https://github.com/mandiant/capa/issues/1646. Though, at that time, I have not …

Test binja 4 0

---

capa/main.py

I noticed that signatures will only load when the backend is vivisect:
https://github.com/mandiant/capa/blob/7debc54dbd90372af8f4e3b1819fe632afdaa3fa/capa/main.py#L695-L698
I moved the debug logging from `handle_common_args` to `get_signatures_from_cli`, so it's only printed when the signatures are actually used. This means that other backends don't need the default signatures directory to exist.
Closes #1875

Restrict signature debug logging to vivisect backend

---

capa/features/extractors/binexport2/basicblock.py

`idx.target_edges_by_basic_block_index[basic_block_index]` is of type `List[Edges]`. The index `basic_block_index` was definitely not an element.

Fix BinExport's "tight loop" feature extraction.

---

pyproject.toml

I think any pydantic major updates were disabled in https://github.com/mandiant/capa/pull/1673, so hopefully this enables them again.

Update pydantic to 2.7.1

---

capa/capabilities/static.py

When emitting log message, show the number of "real" rule matches, ignoring any of the derived subscope rule matches, which account for most matches.

capabilities: only log "real" matched rules, not derived count

---

capa/engine.py
capa/features/common.py
tests/test_engine.py

It was used in some places already, but now used everywhere consistently. This should make it easier to refactor the FeatureSet type, if necessary, because its easier to see all the places its used.

engine, common: use FeatureSet type annotation for `evaluate` signature

---

CHANGELOG.md
capa/features/extractors/cape/models.py

support more report formats

---

scripts/profile-time.py

Output looks like:
which renders to this on Github:
| feature class                      | evaluation count   |
|------------------------------------|--------------------|
| evaluate.feature                   | 19,939,641         |
| evaluate.feature.and               | 4,441,407          |
| evaluate.feature.rule              | 4,124,464          |
| evaluate.feature.api               | 2,385,944          |
| evaluate.feature.bytes             | 1,756,958          |
| evaluate.feature.match             | 1,546,698          |
| evaluate.feature.or                | 1,443,142          |
| evaluate.feature.number            | 1,246,595          |
| evaluate.feature.mnemonic          | 1,205,911          |
| evaluate.feature.regex             | 271,779            |
| evaluate.feature.os …

profile-time: more result reporting, and learn to specify other backends

---

capa/features/extractors/binexport2/__init__.py
capa/features/extractors/binexport2/basicblock.py
capa/features/extractors/binexport2/extractor.py
capa/features/extractors/binexport2/file.py
capa/features/extractors/binexport2/function.py
capa/features/extractors/binexport2/helpers.py
capa/features/extractors/binexport2/insn.py

binexport: add typing where applicable

---

CHANGELOG.md
capa/engine.py
capa/features/common.py
capa/rules/__init__.py
tests/test_match.py
tests/test_scripts.py

(continuation of #2080 rebased against master)
Implement the "tighten rule pre-selection" algorithm described here: https://github.com/mandiant/capa/issues/2063#issuecomment-2100498720
In summary:
> Rather than indexing all features from all rules,
> we should pick and index the minimal set (ideally, one) of
> features from each rule that must be present for the rule to match.
> When we have multiple candidates, pick the feature that is
> probably most uncommon and therefore "selective".
This seems to work pretty well. Total evaluations when running against mimikatz drop from 19M to 1.1M (wow!) and capa seems to match around 3x more functions per second (wow wow).
When doing large scale runs, capa is about 25% faster when using the vivisect backend (analysis heavy) or 3x faster when using …

optimize rule matching by better indexing rule by features

---

.github/workflows/build.yml
.github/workflows/publish.yml
.github/workflows/tests.yml
CHANGELOG.md
doc/installation.md
pyproject.toml
requirements.txt

closes #2053
closes #2079
```py
#
#
#
#
```

relax pyproject dependency versions and introduce requirements.txt

---

CHANGELOG.md
pyproject.toml
scripts/capa2sarif.py
tests/test_scripts.py

SARIF gets you navigation for binary beacons from capa in any tool that supports SARIF(e.g., ghidra/radare/ida). I expect this to be a core format for binary analysis in the future.
The Static Analysis Results Interchange Format (SARIF) is a standardized format for the output of static analysis tools, which are used to evaluate source or binary for things like vulnerabilities or dataflow. SARIF enables different analysis tools to produce results in a common format that can be easily understood, integrated, and acted upon by software development tools and systems. E.g. vscode, ghidra, radare2, and github all adopt a common standard for representing types of information.
SARIF describes: the analysis being ran and results from an analysis on an artifact. Results include description of …

FEAT(capa2sarif) Add SARIF conversion script from json output

---

capa/features/extractors/dnfile/helpers.py
capa/features/extractors/dotnetfile.py
pyproject.toml

dnfile v0.15.0 contains a breaking change.  The heap streams' .get() functions now return custom container objects instead of bytes.
I think I changed the necessary parts to keep same functionality, but am not definite.  If necessary, feel free to close this PR and handle as you see fit.  I just wanted to make it easier to integrate the breaking change.

dnfile 0.15.0 changed API

---

.github/workflows/tests.yml
CHANGELOG.md
doc/installation.md
pyproject.toml
scripts/capa2sarif.py
tests/test_scripts.py

fix black and mypy

---

.pre-commit-config.yaml
CHANGELOG.md
capa/features/extractors/elf.py
capa/loader.py
pyproject.toml
tests/fixtures.py
tests/test_os_detection.py

use the strategies pioneered by GoReSym to detect the target OS for ELF binaries compiled by Go:
- find the GOOS configuration, and
- find embedded Go source filenames
closes #1978
FYI @C0d3R3ad3r
FYI @stevemk14ebr

ELF: Detect OS from Go binaries

---

CHANGELOG.md
capa/version.py

bump to v7.1.0

---

capa/features/extractors/binja/extractor.py
scripts/import-to-bn.py

1) Suppress binja warning: 5721a2f80d93feee5d91eee83d92aab0182a0fb1
2) Update/fix binja plugin with the latest dev version (4.1.5703-dev (c377d19e)) : 04cea3dd591f5b71b1a5a5da8d27c0a0fcb38de6

Binary Ninja update and fix

---

.github/workflows/tests.yml
CHANGELOG.md
tests/test_binja_features.py

closes #2211
1. I have updated the binja version check to 4.1 since we have just released it
2. I have updated the CI workflow to use Python 3.9 to test it because we dropped support for Python 3.8

Update Binary Ninja version to 4.1 and use Python 3.9 to test it

---

CHANGELOG.md
capa/features/extractors/elffile.py
capa/loader.py
capa/main.py

such as when there's a missing symbol table and invalid relocation table. and then handle when Viv fails to load a workspace.
closes #2226

ELF: better handle corrupt files

---

capa/rules/__init__.py

#2119 issue: use bytes.fromhex instead of binascii

---

.github/workflows/tests.yml
CHANGELOG.md

closes https://github.com/mandiant/capa/issues/2256
Update tests.yml CI workflow to exclude `web/`, `doc/` and Markdown files
This PR modifies the tests.yml workflow to:
- Ignore changes in the 'web/' and `doc/` directory
- Ignore changes to Markdown files (.md) throughout the repository
- Run tests and checks for all other file changes
Let's first try and merge this PR and use [#2258](https://github.com/mandiant/capa/pull/2258) as a test example.

add path exclusions to python tests.yml workflow

---

web/explorer/src/components/NavBar.vue
web/explorer/vite.config.js

closes https://github.com/mandiant/capa/issues/2266 (and https://github.com/mandiant/capa/issues/2262) 
This PR changes the base url of capa Explorer Web to `/capa/explorer` so that it can be hosted on `mandiant.github.com/capa/explorer`

web: change base url for capa Explorer Web

---

web/explorer/index.html
web/explorer/src/components/columns/RuleColumn.vue

web: fix build warnings

---

.github/workflows/web-deploy.yml
web/explorer/package.json
web/explorer/src/components/NavBar.vue

This PR
- fixes a a typo in package.json
- moves the zip asset to the public dir.
Note: `public` dir is a special dir which hosts files that would be served as is, so it makes sense to put the release for download there.

use relative path for zip release asset

---

CHANGELOG.md
README.md
capa/features/extractors/ida/insn.py
capa/ida/plugin/README.md
pyproject.toml

Add support to extract dynamically resolved APIs stored in global variables that have been renamed (for example using the `renimp.idc` script included with IDA Pro).
It supports (and may close if we do not want to support the extraction of other types of API dynamic resolution) https://github.com/mandiant/capa/issues/252

ida extractor: extract APIs from renamed globals

---

web/explorer/src/App.vue
web/explorer/src/components/FunctionCapabilities.vue
web/explorer/src/components/ProcessCapabilities.vue
web/explorer/src/components/RuleMatchesTable.vue
web/explorer/src/composables/useRdocLoader.js
web/explorer/src/router/index.js
web/explorer/src/store/rdocStore.js
web/explorer/src/views/AnalysisView.vue
web/explorer/src/views/ImportView.vue

closes #2286, #2291 and https://github.com/mandiant/capa/issues/2259#issuecomment-2277682013
The following PR introduces a new view `AnalysisView.vue`, to which the user is redirected to upon uploading a new rdoc.
Preview this PR here: [s-ff.github.io/capa/explorer](https://s-ff.github.io/capa/explorer/#/)

web: diplay results in new /analysis route

---

web/explorer/src/components/NavBar.vue

resolves https://github.com/mandiant/capa/issues/2286#issuecomment-2286392406 and https://github.com/mandiant/capa/issues/2286#issuecomment-2286637495
<details><summary>moves FLARE logo to the right left side, and make a clickable link to / </summary>
</details>

rearrange navbar icons

---

web/explorer/src/components/FunctionCapabilities.vue
web/explorer/src/components/RuleMatchesTable.vue
web/explorer/src/components/SettingsPanel.vue
web/explorer/src/views/AnalysisView.vue

closes #2288, #2289, #2290 and partially fixes #2287
This PR:
- fixes global search in show capabilities by function
- introduces search column filters in show capabilities by function (off by default)
- uses a bold color separator
- reintroduces the toggle icon (`>`)

web: fix global search and add UI tweaks

---

web/explorer/src/components/RuleMatchesTable.vue

closes #2236
<details><summary>This PR adds support for copying rule name and adds a description to the VT deep link</summary>
</details>

web: add copy rule name and description to VT to right click menu

---

web/explorer/src/components/FunctionCapabilities.vue
web/explorer/src/components/columns/RuleColumn.vue
web/explorer/src/utils/rdocParser.js

This PR resolves the items:
> - [x] allow users to hover over a hex feature value to view its decimal representation
> - [x] show capas by function: include file level matches in section as a table row

web: add file scope rules and display decimal repr for hex values

---

web/explorer/index.html
web/public/index.html

Public metrics URL here: https://cloud.umami.is/share/rVo8TE6uNFsCi0aw/mandiant.github.io
We plan to use this analytics script to collect pageview metrics, since the capa website is hosted on GH Pages and they don't share the raw access logs. Umami is a privacy focused analytics solution, and we're impressed by their commitments and open source releases. We publish the above link so that its clear to anyone the sorts of information that are collected: # of page loads over time, essentially.

web: add umami script for collecting metrics

---

web/explorer/src/components/NavBar.vue
web/explorer/src/components/RuleMatchesTable.vue
web/explorer/src/components/UploadOptions.vue
web/explorer/src/components/columns/RuleColumn.vue
web/explorer/src/composables/useRdocLoader.js
web/explorer/src/utils/rdocParser.js
web/explorer/src/views/ImportView.vue
web/explorer/vite.config.js

closes #2285
closes #2259 
This PR -
- disables the preview data buttons from being displayed and excludes the test files from the build and release.
- bumps the number of matches in dynamic to 300 instead of 1 (still slow, but manageable)
- extend `rdoc` query param to support loading remote `.gz` files.
- refactors `parseRules` used to parse the rdoc rules.
Please preview this PR here: https://s-ff.github.io/capa/explorer

web: don't include preview data and options in release mode

---

CHANGELOG.md
capa/rules/__init__.py

rules: deduplicate API features with stripped DLL

---

.justfile
CHANGELOG.md

This PR adds a "justfile", which is a configuration file for the tool [just](https://github.com/casey/just). Just is a command runner, like a simplified Make.
I've been having trouble remembering the pre-commit command line invocations needed to run the various linters. Some need `--hook-stage manual` and others don't. Usually I use my shell's history to find the command I need, but its painful when I move to a new system. I want to use Just to hide all these extra flags away, so I can just type:
```console
just isort
```
```console
just isort black
```
```console
just lint
```
The configuration file is hidden, that is, the filename is `.justfile`, so it won't show up in most directory listings. I'm not sure that we have to add even more documentation about this file, though I'm happy to …

add .justfile

---

README.md
web/explorer/DEVELOPMENT.md
web/explorer/README.md
web/explorer/index.html
web/explorer/src/components/DescriptionPanel.vue
web/explorer/src/components/MetadataPanel.vue
web/explorer/src/components/NavBar.vue
web/explorer/src/components/UploadOptions.vue
web/explorer/src/main.js

closes #2272
closes #2219
This PR
- updates the project READMEs to use `capa explorer web` as a title
- adds a simple landing page message to help new users to navigate to the repo for instructions
- adds minor styling tweaks 
preview landing page here: [s-ff.github.io/capa/explorer/](https://s-ff.github.io/capa/explorer/#/)
I am open to any other suggestions

Edit explorer landing page

---

web/explorer/src/utils/rdocParser.js

capa JSON output with dnfile uses `class_` instead of `class` for feature types. This PR fixes a bug that shows undefined for `class` feature types.
Example: rule `encrypt data using AES via .NET` in https://mandiant.github.io/capa/explorer/#/?rdoc=https://dpaste.org/wEWd9/raw

web: fix class feature type

---

.justfile
CHANGELOG.md
capa/render/default.py
tests/test_render.py
web/explorer/src/components/RuleMatchesTable.vue
web/explorer/src/utils/urlHelpers.js
web/public/index.html
web/rules/.gitignore
web/rules/scripts/build_root.py
web/rules/scripts/build_rules.py

closes #2337 
closes #2319
Add modern terminal markup to hyperlink to resources on the web, like entries on the capa rules website.
To make this possible, use rich instead of tabulate to render tables.
Also update the canonical path to rules on the website, to: mandiant.github.io/rules/[rule name]/
Using the rule name from the rule header makes it very easy to generate links to the web pages, rather than using the filename of the rule.

cli: link to rule names to capa rules website

---

web/explorer/src/utils/urlHelpers.js

resolves https://github.com/mandiant/capa/pull/2338#issuecomment-2318270162
remove `tag` param from the function definition, otherwise this function will always return `null`

web: omit unneeded function param in createCapaRulesUrl

---

CHANGELOG.md
capa/features/extractors/ida/file.py
capa/features/extractors/ida/global_.py
capa/features/extractors/ida/helpers.py
capa/ida/helpers.py
pyproject.toml

closes #2311 
WIP as we need to figure out how to use 8.0 and 9.0 APIs
currently this should work just for IDA Pro 9.0 only though

use new IDAPython 9.0 APIs

---

CHANGELOG.md
capa/helpers.py

cache: use path to code, not hardcoded relative path

---

.github/workflows/web-deploy.yml
CHANGELOG.md
README.md
capa/main.py
web/explorer/.prettierrc.json
web/explorer/DEVELOPMENT.md
web/explorer/README.md
web/explorer/index.html
web/explorer/src/components/BannerHeader.vue
web/explorer/src/components/DescriptionPanel.vue
web/explorer/src/components/MetadataPanel.vue
web/explorer/src/components/NavBar.vue
web/explorer/src/components/ProcessCapabilities.vue
web/explorer/src/components/RuleMatchesTable.vue
web/explorer/src/components/SettingsPanel.vue
web/explorer/src/components/columns/RuleColumn.vue
web/public/index.html

extend text on home page and update to use `capa Explorer Web` throughout. 
preview

Update web pages

---

capa/features/extractors/binexport2/__init__.py
capa/features/extractors/binexport2/arch/arm/insn.py
capa/features/extractors/binexport2/arch/intel/insn.py
capa/features/extractors/binexport2/helpers.py
scripts/inspect-binexport2.py
tests/fixtures.py
tests/test_binexport_accessors.py

This PR against the BinExport2 PR introduces a way to match instructions and extract expression values. We use this mini-language to specify how to extract features from BinExport2 instructions, such as Number, Offset, nzxor, etc. While there's a fair amount of code (~500 lines, with tests) to implement this matching language, it is:
1. more human readable
2. less fragile
3. better tested
4. and therefore more maintainable (I think).
To understand all the changes here, I'd recommend reading:
1. https://github.com/mandiant/capa/commit/2cff6333c1ac83dc514eec61656d2a4ff19c2c51: consolidate expression tree handling. Specifically, this introduces fixes for Ghidra BinExport2 containing `lsl #0` expressions that have no effect. We prune these from the expression tree.
2. …

match BinExport2 instructions using patterns

---

.github/pyinstaller/pyinstaller.spec
.gitignore
CHANGELOG.md
capa/features/extractors/binja/file.py
capa/features/extractors/binja/find_binja_api.py
capa/features/extractors/ida/extractor.py
capa/features/extractors/ida/idalib.py
capa/helpers.py
capa/ida/helpers.py
capa/loader.py
capa/main.py
pyproject.toml
scripts/compare-backends.py
scripts/detect-backends.py

detect and use third-party analysis backends when possible

---

CHANGELOG.md
capa/features/extractors/vmray/__init__.py
capa/features/extractors/vmray/extractor.py
capa/features/extractors/vmray/file.py
capa/features/extractors/vmray/models.py
tests/fixtures.py
tests/test_vmray_features.py

Fix VMRay missing process data

---

capa/loader.py

it was possible that loading the workspace could raise an exception that would get swallowed, but `vw` wasn't bound. this ensures the exception is always raised.
the exception that i saw get swallowed was "unsupported architecture" like 32-bit armv8.

loader: fix unhandled name error

---

CHANGELOG.md
web/explorer/src/router/index.js

closes #2419 
This PR enhances the navigation in capa Explorer Web by making sure the links generated are shareable. [Preview](https://s-ff.github.io/capa/explorer/#/analysis?rdoc=https://raw.githubusercontent.com/mandiant/capa-testfiles/master/rd/al-khaser_x64.exe_.json).
Previously: users browsing to `/analysis` were always redirected to the homepage `/`.
With this PR:
- If a user accesses `/analysis` without an rdoc query parameter set in the URL, they are still redirected to the homepage.
- If a user accesses `/analysis` with the rdoc query parameter set, capa Explorer Web loads from that URL instead of redirecting to homepage.

capa Explorer Web: improve url navigation

---

CHANGELOG.md
capa/features/extractors/vmray/call.py
tests/test_vmray_features.py

fix backslash handling in string call arguments

---

CHANGELOG.md
capa/ghidra/capa_explorer.py
capa/ghidra/capa_ghidra.py
capa/main.py
capa/version.py
doc/release.md

Release v7.4.0

---

CHANGELOG.md
capa/features/extractors/ida/helpers.py
capa/features/extractors/ida/idalib.py
capa/loader.py
pyproject.toml

Fix IDA 9.0 / idalib

---

web/explorer/src/components/RuleMatchesTable.vue
web/explorer/src/components/columns/RuleColumn.vue

closes #2434
[Preview](https://s-ff.github.io/capa/explorer/#/analysis?rdoc=https://raw.githubusercontent.com/mandiant/capa-testfiles/master/rd/0000a65749f5902c4d82ffa701198038f0b4870b00a27cfca109f8f933476d82.json.gz)
wrap long API calls to 120 characters per line

webui: wrap long function calls

---

CHANGELOG.md
capa/ghidra/helpers.py
capa/ida/helpers.py

noticed that this wasn't handled properly

fix save base address

---

.github/workflows/web-release.yml
.github/workflows/web-tests.yml
CHANGELOG.md
web/explorer/.gitignore

closes https://github.com/mandiant/capa/issues/2364

ci: add web releases workflow

---

CHANGELOG.md
capa/rules/__init__.py

naive fix
questions?
- does this suffice / result in unwanted side behavior (current tests pass)
- add new tests?
- update docs?

allow call as valid subscope for call scoped rules

---

CHANGELOG.md
capa/features/extractors/binja/extractor.py
capa/features/extractors/binja/file.py
capa/features/extractors/binja/function.py
capa/features/extractors/binja/insn.py
tests/test_binja_features.py

This PR fixes:
1. https://github.com/mandiant/capa/issues/2499
2. https://github.com/mandiant/capa/issues/2489
3. https://github.com/mandiant/capa/issues/2249

Various binja backend fixes

---

CHANGELOG.md
capa/features/extractors/binja/function.py
capa/features/extractors/binja/helpers.py
capa/features/extractors/binja/insn.py

This is part of the effort to optimize the binja extractor performance (#1414). As I mentioned in https://github.com/mandiant/capa/pull/2509#issuecomment-2507409096, one of the outstanding issue that drags down the binja extractor performance is the re-generation of the IL functions during feature extraction. Those are, however, necessary to ensure the most accurate results.
That said, I found that we can actually just retrieve a single LLIL instruction instead of requesting the entire IL from the function. Getting an LLIL instruction is extremely fast compared to getting the entire IL function and then take the particular instruction from it. 
Here is what I am getting as a difference:
1. For a small file (321338196a46b600ea330fc5d98d0699.exe_, 486 KB in size), the feature extracting …

binja: retrieve the LLIL instruction itself without requesting the entire IL function

---

CHANGELOG.md
capa/features/extractors/cape/models.py

make Process model flexible and procmemory optional

---

CHANGELOG.md
capa/features/extractors/vmray/__init__.py
capa/features/extractors/vmray/extractor.py
capa/features/extractors/vmray/models.py

vmray: record command line info

---

CHANGELOG.md
capa/features/extractors/binja/insn.py
tests/fixtures.py
tests/test_binja_features.py

This provides a better fix for #2507 by fixing up the binja analysis (i.e., manually defining the function at 0x14004b4f0)
This issue also exposes a bug when I previously introduced the optimization in https://github.com/mandiant/capa/commit/b6763ac5fe72034cf841d401a1188c06bf0a0af3. It is not fixed in this PR as well

binja: fix up analysis for the al-khaser_x64.exe_ file

---

CHANGELOG.md
capa/features/extractors/binexport2/__init__.py

binexport2: fix handling of incorrect thunks

---

CHANGELOG.md
capa/features/extractors/binexport2/helpers.py
scripts/inspect-binexport2.py

more precise pruning of BinExport2 expressions. better rendering, too.

BinExport2: better expression pruning

---

CHANGELOG.md
capa/features/extractors/binexport2/helpers.py
capa/main.py
scripts/inspect-binexport2.py

BinExport2: better handle weird expression trees

---

CHANGELOG.md
capa/version.py
doc/release.md
web/public/index.html

release v8.0.0

---

CHANGELOG.md
capa/features/extractors/ida/helpers.py

Classic just after doing the release...
https://github.com/mandiant/capa/pull/2339/files only updated for 9.0 and we did not add support for 8.X afterwards.

handle IDA 8.3/8.4 vs. 9.0 API change

---

CHANGELOG.md
capa/features/extractors/vmray/__init__.py
capa/features/extractors/vmray/models.py
capa/main.py
tests/test_vmray_model.py

A few improvements based on analysis of around 200 random VMRay archives.

VMRay and dynamic improvements

---

README.md

readme: avoid scroll on github homepage

---

CHANGELOG.md
capa/features/extractors/vmray/__init__.py
capa/features/extractors/vmray/extractor.py
capa/features/extractors/vmray/file.py
capa/features/extractors/vmray/global_.py
scripts/minimize_vmray_results.py
tests/fixtures.py
tests/test_vmray_features.py

closes #2403 
This PR addresses two issues:
1. Loosen file checks to enable processing of additional file types, e.g. PS1 and MSI. We handle this by largely ignoring _file_ and _global_ feature extraction because we care most about the dynamic trace analysis anyways. This accepts that capa's results may be incomplete but still useful.
2. Handle VMRay analysis archives that may have more than one file marked as the submission, e.g. compound ZIP files. Unfortunately, I have not identified a sure way of differentiating which of the files is the actual submission. Instead, we rely on the ordering of the files and use the last file marked as the submission file. This appears to hold true for compound ZIP files.

vmray: loosen file checks to enable processing of additional file types

---

CHANGELOG.md
scripts/lint.py

closes #2124
```
❯ python scripts/lint.py rules/
INFO     lint: collecting potentially referenced samples                                                                                                           lint.py:1090
acquire debug privileges
FAIL: rule dependency scope mismatch: rule 'acquire debug privileges' (Scope.BASIC_BLOCK) depends on rule 'modify access privileges' (Scope.FUNCTION).
check mutex
FAIL: rule dependency scope mismatch: rule 'check mutex' (Scope.BASIC_BLOCK) depends on rule 'create mutex' (Scope.FUNCTION).
delete drive layout via IOCTL
FAIL: rule dependency scope mismatch: rule 'delete drive layout via IOCTL' (Scope.CALL) depends on rule 'interact with driver via IOCTL' (Scope.THREAD).
(nursery)  persist via application shimming
WARN: missing examples: Add …
```

feat: add lint to validate rule dependency scope compatibility

---

CHANGELOG.md
capa/rules/__init__.py
scripts/lint.py
tests/test_rules.py

Allows us to do this (note the subscope blocks match the rule scopes):
```yml
rule:
meta:
scopes:
static: basic block
dynamic: span of calls
features:
- or:
- basic block:
api: CreateFileW
- span of calls:
api: CreateFileZ
```
This enables us to have a block only match in either static/dynamic mode (in a slightly hacky way).
See thread here:
https://github.com/mandiant/capa-rules/pull/987/files#r1936164120
Note that we already supported this sort of behavior for `match` statements that referenced a rule with the same scope. Now we're enabling the same behavior for subscope statements. Because `match` and subscopes use the same implementation, I don't expect there to be much risk here.

rules: scopes can now have subscope blocks with same scope

---

CHANGELOG.md
capa/features/extractors/cape/models.py

Only parse the CAPE fields required for analysis and ignore the rest. This drastically reduces the bug surface and number of CAPE models that we must maintain to avoid pydantic errors (e.g. #2539). Fields that were never used have been commented out (to remain as documentation) and we can add fields back in the future, as/if needed.
Fixes #2539.

cape: models: parse minimum fields required for analysis

---

CHANGELOG.md
scripts/lint.py

see https://github.com/mandiant/capa-rules/pull/1026 for an example of how unescaped `.` can results in FPs. This adds a WARN for regular expressions that contain unescaped `.`.

lint: add WARN for regex features that contain unescaped dot

---

CHANGELOG.md
scripts/lint.py

add lint for registry control set regex that is not complete

---

.github/workflows/build.yml
.github/workflows/tests.yml

ubuntu-20.04 has been deprecated causing several GH actions to fail: https://github.com/actions/runner-images/issues/11101
Without this change, the CI will start failing (it started failing 2 days ago in VM-Packages).

ci: Update Ubuntu version in actions

---

.github/workflows/build.yml
CHANGELOG.md

Closes https://github.com/mandiant/capa/issues/2690
One exception, Windows 11 ARM seems to complain of Python incompatibility (from https://github.com/heywoodlh/capa/actions/runs/15566091415/job/43830414447):
```
ERROR: Cannot install None, flare-capa[build]==9.2.1, viv-utils[flirt]==0.7.10, viv-utils[flirt]==0.7.11, viv-utils[flirt]==0.7.12, viv-utils[flirt]==0.7.13, viv-utils[flirt]==0.7.9 and viv-utils[flirt]==0.8.0 because these package versions have conflicting dependencies.
The conflict is caused by:
flare-capa 9.2.1 depends on viv-utils>=0.7.9
flare-capa[build] 9.2.1 depends on viv-utils>=0.7.9
viv-utils[flirt] 0.8.0 depends on viv-utils 0.8.0 (from https://files.pythonhosted.org/packages/e2/ee/da45fa8057dc76b856ad19759299dcc3163dc764fefe18014a8bfd69b339/viv_utils-0.8.0-py2.py3-none …
```

added arm64 binary release support

---

.github/workflows/build.yml
CHANGELOG.md

ci: remove redundant "test_run" action

---

pyproject.toml

`ida-settings` 3.0.0 has breaking changes (`IDASettings` not exported). Pinning to 2.1.0 is ideal until work has been done to address these changes.

Pin ida-settings version to 2.1.0
