mandiant/capa

- capa/render/vverbose.py
also found a second TypeError when looking around the same file.
thanks @re-fox!
closes #182
> render: vverbose: fix type error

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- doc/installation.md
Document supported Linux distributions, improve cloning capa source code documentation and issue templates. :bowtie:
> Improve documentation

- capa/main.py
> fix: disable progress when run in quiet mode

- capa/ida/helpers/__init__.py
- capa/ida/ida_capa_explorer.py
- capa/main.py
tested in all listed versions on Windows
closes #179
> capa explorer plugin: assert IDA version

- .github/workflows/tests.yml
- capa/features/extractors/viv/insn.py
- tests/test_viv_features.py
might need some updates to the IDA backend to bring this to parity.
closes #200
> features: viv: extract strings/bytes from nested pointers

- .github/pyinstaller/pyinstaller.spec
- .github/workflows/build.yml
- setup.py
unfortunately, haven't tested the "upload to release page" functionality yet, since we don't have a tag.
closes #178
> ci: enable pyinstaller builds upon gh release tagged

- .github/workflows/build.yml
- setup.py
> setup: bump viv version

- capa/features/extractors/ida/__init__.py
- capa/features/extractors/ida/insn.py
- tests/test_ida_features.py
> ida: use a local context for cache instead of global

- capa/features/extractors/ida/insn.py
- capa/features/extractors/viv/insn.py
- tests/fixtures.py
- tests/test_viv_features.py
> adding support to emit number features for unmapped immediate memory references

- capa/features/extractors/ida/helpers.py
- capa/features/extractors/ida/insn.py
- tests/test_ida_features.py
> IDA: resolve nested data references to strings/bytes

- capa/features/extractors/viv/insn.py
- capa/main.py
- setup.py
two things:
1. compute the full function list (rather than iterator) so that tqdm knows the total expected function count and can estimate duration
2. show progress bar when loading rules, which can take a few seconds on slower systems (3-4s on my laptop when on battery power)
there will still be a black hole in the output while viv does its initial analysis. i dont think we can display a progress bar for workspace creation, unfortunately.
> main: progress bar updates (+rules, and realize iterators)

- .github/workflows/tests.yml
- capa/features/__init__.py
- capa/features/freeze.py
- tests/fixtures.py
- tests/test_freeze.py
- tests/test_main.py
- tests/test_rules.py
- tests/test_viv_features.py
please merge #239 first, then the delta will simplify
> fix 241: string counting exception

- capa/rules.py
- tests/test_rules.py
> bugfix 249

- capa/features/extractors/ida/basicblock.py
- capa/features/extractors/ida/file.py
- capa/features/extractors/ida/function.py
- capa/features/extractors/ida/helpers.py
- capa/features/extractors/ida/insn.py
- capa/features/extractors/loops.py
- capa/features/freeze.py
- capa/ida/explorer/item.py
- capa/ida/explorer/model.py
- capa/ida/explorer/proxy.py
- capa/ida/explorer/view.py
- capa/ida/helpers/__init__.py
- capa/ida/ida_capa_explorer.py
- capa/main.py
- capa/render/__init__.py
- capa/render/default.py
- scripts/import-to-bn.py
- scripts/import-to-ida.py
- scripts/lint.py
- scripts/show-capabilities-by-function.py
- setup.py
- tests/fixtures.py
- tests/test_engine.py
- tests/test_freeze.py
- tests/test_main.py
- tests/test_rules.py
- tests/test_viv_features.py
New black version demands changes.
Had to do dos2unix on the 2 scripts/import-to* to get this to pass as well.
Do we want to pin to a specific version to avoid this confusion?
> Black reformat

- capa/ida/explorer/proxy.py
- capa/ida/ida_capa_explorer.py
Adds code to include basic block scope when limiting results by function in the tree view:
> explorer: improve limit by function capability

- .github/pyinstaller/pyinstaller.spec
- .github/workflows/publish.yml
- doc/usage.md
- setup.py
closes #254 use vivisect from pypi
closes #154 push capa to pypi
> use vivisect from pypi and other packaging

- capa/ida/plugin/form.py
- setup.py
> ida: use ida-settings to persist rules directory

- capa/render/default.py
- tests/test_main.py
closes #224
before:
after:
note the TCP socket matches are more concise.
> render: dont display rules that are also matched as subrule matches

- capa/ida/plugin/form.py
- capa/ida/plugin/model.py
- capa/ida/plugin/proxy.py
- capa/ida/plugin/view.py
Brings new features and performance enhancements to IDA plugin:
Features:
- tree view: `Rule Information` column maximum size enforced
- tree view: horizontal scrollbar enabled
- tree view: new label added to show number of rules loaded from rules directory
- tree view: searching for keywords retains level 1 tree expansion for easier navigation
Performance:
- tree view: eliminated dependency loop that resulted in unnecessary overhead
Documentation:
- updated function-level documentation
- updated the function names of slot functions to make their intention clearer
> ida plugin: performance enchancements

- doc/installation.md
> docs: installation: clarify when to use method 2

- capa/ida/plugin/form.py
Addresses #300.
Features:
* display progress for rule loading and feature extraction
* user can cancel analysis at any time
Bug fixes:
* reset IDA highlighting before program rebase
* reset IDA highlighting before new analysis is performed
* only restart capa analysis if image base actually changes when user elects to change program base
> explorer: progress indicator

- capa/ida/plugin/view.py
> explorer: add additional check for invalid model index

- scripts/bulk-process.py
runs in subprocesses by default for parallelism:
output is a json document mapping file paths to results:
closes #307
> scripts: add script demonstrating bulk processing

- capa/main.py
> main: fix reported total rule count

- capa/engine.py
- capa/rules.py
- tests/test_rules.py
> parse descriptions for statements

- capa/render/default.py
Add rendering of MBCs after @dzbeck's rule updates in https://github.com/fireeye/capa-rules/pull/110 and https://github.com/fireeye/capa-rules/pull/138.
> render mbc table

- capa/features/extractors/ida/file.py
- capa/features/extractors/ida/helpers.py
> modify find_byte_sequence to yield all locations

- capa/features/__init__.py
> fix feature display

- .github/workflows/build.yml
ref: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
> set env var via environment file

- capa/features/__init__.py
- capa/features/extractors/ida/insn.py
- capa/features/extractors/viv/helpers.py
- capa/features/extractors/viv/insn.py
- scripts/show-features.py
- tests/fixtures.py
> extract api features for thunk chains

- scripts/show-features.py
ensure function is defined in vivisect (or do so) and show features in IDA
> Enhancements to show-features script

- capa/main.py
- tests/fixtures.py
- tests/test_main.py
> get decoded sample path

- .github/workflows/build.yml
recommend merge this, then release v1.4.1 and update the v1.4.0 release notes to point to v1.4.1 for standalone binary.
> fix build on windows-latest

- doc/installation.md
> document PyInstaller build process

- .github/workflows/tests.yml
> ci: disable py3.9 testing

- capa/features/extractors/viv/insn.py
- tests/fixtures.py
> improve viv extractor unicode string detection

- scripts/capa_as_library.py
Just quick example how to use capa as library, to save time to someone, reading code and scripts
> Simple example how to use capa as library

- .github/dependabot.yml
- setup.py
likely need to ignore some dependencies, see https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates#ignore
closes #371
> add dependabot config

- scripts/lint.py
required for https://github.com/fireeye/capa-rules/pull/214
> lint with tags

- capa/features/freeze.py
fixes issue when saving/loading freeze files
> add base address to freeze

- .github/workflows/tests.yml
- setup.py
> bump smda, enable Python 3.9

- .github/workflows/tests.yml
> Disable Python 3.6 tests

- scripts/lint.py
adjustments to help debug #427 in GitHub Actions, as local results differ
> disable extractor progress

- capa/features/extractors/ida/helpers.py
- capa/features/extractors/ida/insn.py
- capa/features/extractors/viv/insn.py
- tests/fixtures.py
- reduces `FF FF FF FF ...` bytes sequences extracted by IDA
- small viv optimization
> improve bytes feature extraction

- capa/features/extractors/smda/insn.py
> remove apirefs from calls from

- setup.py
> setup: pin viv-utils version

- scripts/lint.py
Adding lint to warn users of potential export overlap between `ntdll` and `ntoskrnl`.
Because we do not include a known list of overlaps to check we can't treat this as a failed lint because an export very well may exist in only `ntdll` or `ntoskrnl` and we should allow a user to write their rule accordingly. Therefore, we also add the ability to specify a lint level of `WARN` or `FAIL`, so we can write lints that simply inform users how they could improve a rule, but don't necessarily prevent the rule from being valid.
e.g.
```
C:\Exclusions\capa>python scripts\lint.py rules\host-interaction\log\debug\write-event\print-debug-messages.yml
INFO:capa.lint:successfully loaded 1 rules
INFO:capa.lint:collecting potentially referenced samples
print debug messages
WARN: feature api may overlap …
```
> linter: adding ntoskrnl, ntdll overlap lint

- capa/ida/plugin/form.py
- capa/ida/plugin/view.py
users can now generate rules at file scope; plugin supports extracting file/function/basic block features to display in the UI and checks matches at file/function/basic block scopes.
both file and function/basic block features are displayed if a user has navigated to a function in the IDA disassembly view, otherwise only file features are displayed.
> adding file scope support to rule generator IDA plugin

- setup.py
supersedes #413
closes #385
closes #201
> setup: bump viv to 0.2.1

- README.md
> Update README.md with Python version badge

- capa/ida/plugin/view.py
addresses #471.
https://user-images.githubusercontent.com/42192796/110872888-e04bdd80-828d-11eb-861b-e89fbf64679f.mov
> explorer: adding support for multi-line tab and SHIFT + Tab

- .github/workflows/build.yml
- .github/workflows/publish.yml
- .github/workflows/tests.yml
> ci: pin OS versions

- capa/ida/plugin/form.py
- capa/ida/plugin/view.py
- adding support for matching rules containing one or more subscopes
- adding support to insert default child statement when creating new `basic block` subscope
https://user-images.githubusercontent.com/42192796/112070041-8cb17d80-8b32-11eb-9486-07a6ebac7fbb.mov
> rule generator: support subscope rules

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
> fix submodule typos

- capa/ida/plugin/README.md
updating supported IDA Pro versions.
> updating capa explorer doc

- CHANGELOG.md
- capa/main.py
- tests/test_main.py
> auto detect shellcode file extensions

- capa/main.py
- scripts/lint.py
> move auto format check

- .github/workflows/build.yml
- CHANGELOG.md
closes #505
also further discussion is warranted
> build using Py3.8 and test across more OSs

- capa/ida/helpers/__init__.py
> ida: support 7.6

- CHANGELOG.md
- capa/ida/plugin/README.md
> explorer: readme: document IDA 7.6 patch

- CHANGELOG.md
- scripts/show-features.py
> show-features: skip library functions

- CHANGELOG.md
- capa/main.py
- capa/render/verbose.py
- tests/test_main.py
- show identified library function in progress bar
- update rule loading progress bars
- add new field to the `meta` dictionary with library function information
closes #539
> improve progress bar output

- capa/main.py
> lazy import flirt

- CHANGELOG.md
- scripts/lint.py
> linter: summarize status at end

- CHANGELOG.md
- capa/render/__init__.py
- capa/render/default.py
- capa/render/utils.py
- capa/render/vverbose.py
- capa/rules.py
I think a better approach than #574 
closes #526 
> render `rule.meta.mbc` on output

- CHANGELOG.md
- capa/main.py
- capa/render/__init__.py
- capa/rules.py
- scripts/lint.py
> main: use rule scope internal/limitation/file for file limitations, not code

- setup.py
- tests/test_smda_features.py
> bump smda and remove xfail

- .github/workflows/changelog.yml
ignore dependabot for changelog check, see e.g. #609
> ignore dependabot for changelog check

- .github/workflows/changelog.yml
> update dependabot actor name

- CHANGELOG.md
- capa/ida/plugin/__init__.py
> resolve circular import failure

- CHANGELOG.md
- doc/release.md
> changelog: add breaking change section and reorg

- CHANGELOG.md
- capa/main.py
> do not process non-pe even with --format pe

- CHANGELOG.md
- capa/features/extractors/ida/insn.py
> ida extract library funcs identified via flirt

- .github/workflows/tests.yml
- CHANGELOG.md
- capa/main.py
- scripts/show-features.py
- tests/test_scripts.py
> test scripts and fix show-features

- CHANGELOG.md
- capa/ida/plugin/model.py
> add additional filter logic when displaying capa matches by function

- CHANGELOG.md
- capa/ida/plugin/form.py
> remove duplicate check when saving file

- CHANGELOG.md
- capa/features/extractors/ida/insn.py
> update IDA extractor to use non-canon mnemonics

- CHANGELOG.md
- capa/ida/plugin/view.py
> enforce max column width Features and Editor panes

- scripts/capa_as_library.py
update example to work properly on capa v2
> update capa_as_library for capa v2

- setup.py
> Revert "build(deps): bump networkx from 2.5.1 to 2.6.2"

- CHANGELOG.md
- capa/features/common.py
- capa/ida/plugin/model.py
- capa/render/result_document.py
- capa/render/vverbose.py
- capa/rules.py
- scripts/lint.py
- scripts/show-features.py
- tests/fixtures.py
- tests/test_engine.py
- tests/test_rules.py
> rules: add substring feature

- CHANGELOG.md
- capa/features/extractors/base_extractor.py
- capa/features/extractors/ida/extractor.py
- capa/features/extractors/pefile.py
- capa/features/extractors/smda/extractor.py
- capa/features/extractors/viv/extractor.py
- capa/features/freeze.py
- capa/main.py
- tests/fixtures.py
this means they can be extracted separately in the freeze format.
closes #755
> extractors: extract global features as their own pseudo scope

- .github/workflows/build.yml
> update to ubuntu-18.04

- CHANGELOG.md
- capa/ida/plugin/form.py
- capa/ida/plugin/view.py
addresses #745 with improved yaml parsing.
> explorer: improve parsing algorithm for rule generator feature editor

- capa/main.py
> disable flirt matching on elf files

- CHANGELOG.md
- setup.py
closes #702 
closes #704 
closes #705 
closes #706 
closes #708 
closes #710 
closes #711 
closes #712 
closes #713 
closes #714 
closes #735 
closes #744
> setup.py: bump viv dep to v1.0.5

- capa/main.py
- scripts/match-function-id.py
- setup.py
refactored common functionality to viv-utils, depends on https://github.com/williballenthin/viv-utils/pull/19
> use viv-utils functions

- scripts/lint.py
> auto recognize shellcode based on file extension

- CHANGELOG.md
- capa/features/extractors/elf.py
> elf: parse section headers looking for Linux notes, too

- CHANGELOG.md
- capa/features/extractors/ida/helpers.py
remove decorators added by IDA to ELF imports
> fixes #917

- setup.py
fixes Python 10 installation failure
> update pinned smda version

- .github/workflows/build.yml
- .github/workflows/tests.yml
- CHANGELOG.md
- capa/exceptions.py
- capa/features/common.py
- capa/features/extractors/common.py
- capa/features/extractors/dnfile_.py
- capa/features/extractors/dotnetfile.py
- capa/features/freeze.py
- capa/helpers.py
- capa/main.py
- capa/render/json.py
- capa/render/result_document.py
- scripts/lint.py
- scripts/show-capabilities-by-function.py
- scripts/show-features.py
- setup.py
- tests/fixtures.py
- tests/test_dotnet_features.py
detect dotnet files and implement basic dnfile feature extractor
closes #942
closes #943 
closes #944
also refactoring around format and analysis branches
> feat: start dotnet detection

- capa/features/extractors/dnfile_.py
- capa/features/freeze.py
- capa/main.py
- tests/fixtures.py
- tests/test_dotnet_features.py
> fix: imports and add tests

- capa/render/vverbose.py
closes #963
review and merge #973 because i branched from the wrong branch.
> in vverbose mode, show subscope name

- .github/workflows/build.yml
> ci: build: bump pyinstall to v4.10

- capa/rules.py
2nd solution proposed in #1011
thoughts?
> fix: temporarily accept x32/x64 flavors but ignore

- CHANGELOG.md
- capa/features/extractors/dnfile/insn.py
- capa/rules.py
- tests/fixtures.py
includes some code refactoring for dotnet feature extractor.
> dotnet: emit unmanaged call characteristic

- .github/workflows/build.yml
> ci: build on PR

- scripts/lint.py
> feat: lint check value types

- README.md
- capa/ida/plugin/README.md
> readme: fix blog links

- capa/main.py
> main: suppress low level ELF parsing log messages

- CHANGELOG.md
> changelog: document upcoming deprecation of SMDA backend

- capa/render/verbose.py
> render: verbose: render metadata tokens correctly

- capa/rules.py
Reverts mandiant/capa#1014
closes #1016
> Revert "fix: temporarily accept x32/x64 flavors but ignore"

- README.md
- doc/limitations.md
includes updates to README examples.
**Note**: we need to update the blog link before release.
> update documentation for .NET

- scripts/lint.py
> fix: use DnfileFeatureExtractor

- capa/features/extractors/ida/file.py
- capa/ida/plugin/form.py
- capa/ida/plugin/item.py
- capa/ida/plugin/model.py
> fix: string extraction and rendering

- capa/rules.py
> fix #1089: add feature format to global scope

- .github/workflows/build.yml
- CHANGELOG.md
- capa/features/address.py
- capa/ida/helpers.py
- capa/main.py
- capa/version.py
```mermaid
graph TD;
v3-->v4
```
- capa https://github.com/mandiant/capa/compare/v3.2.0...master
- capa-rules https://github.com/mandiant/capa-rules/compare/v3.2.0...master
```commandline
[capa/rules] $ git pull master
[capa/rules] $ git checkout v3  # create if new major version: git checkout -b vX
[capa/rules] $ git merge master
[capa/rules] $ git push origin v3
```
> Release v4.0.0

- .github/pyinstaller/pyinstaller.spec
- CHANGELOG.md
- README.md
> Update document and version set in PyInstaller

- CHANGELOG.md
- capa/version.py
```
-
```
```commandline
[capa/rules] $ git pull master
[capa/rules] $ git checkout v3  # create if new major version: git checkout -b vX
[capa/rules] $ git merge master
[capa/rules] $ git push …
```
> Release v4.0.1

- CHANGELOG.md
- capa/render/vverbose.py
> render: convert feature attributes to aliased dictionary for vverbose

- CHANGELOG.md
- capa/features/address.py
- capa/features/extractors/dnfile/extractor.py
- capa/features/extractors/dotnetfile.py
- capa/features/freeze/__init__.py
- capa/render/verbose.py
- tests/fixtures.py
> fix: use int instead of Token to decouple extractor and features

- .github/pyinstaller/pyinstaller.spec
- CHANGELOG.md
- capa/version.py
> fix: set and parse version string

- CHANGELOG.md
- scripts/import-to-ida.py
> import-to-ida: fix append comment

- .github/mypy/mypy.ini
- scripts/import-to-ida.py
> import-to-ida: use other md5 function

- CHANGELOG.md
- capa/ida/plugin/form.py
- capa/ida/plugin/view.py
> small explorer fixes

- tests/test_smda_features.py
> skip smda tests until we remove the backend

- CHANGELOG.md
- capa/features/extractors/elf.py
- capa/features/extractors/elffile.py
- tests/fixtures.py
- tests/test_os_detection.py
closes #1221
see also https://github.com/mandiant/capa-testfiles/pull/146
> elf: better detect linux ELF files

- tests/test_os_detection.py
> tests: os: fix test

- .github/mypy/mypy.ini
- CHANGELOG.md
- capa/features/extractors/ida/file.py
- capa/features/extractors/ida/helpers.py
- capa/features/extractors/ida/insn.py
- capa/ida/helpers.py
close #1193
**note: this impl. emits `format(pe)` for `COFF` files - open to discussion here.**
> ida: add support for COFF and extern functions

- .github/workflows/build.yml
- .github/workflows/changelog.yml
- .github/workflows/publish.yml
- .github/workflows/tag.yml
- .github/workflows/tests.yml
update CI action images
closes #1232
> ci: bump action versions

- capa/ida/plugin/README.md
> update and remove outdated information

- doc/installation.md
- doc/release.md
- doc/rules.md
supports https://github.com/mandiant/capa-rules/issues/642
> simplified rule release guidance

- capa/ida/plugin/form.py
- capa/main.py
- capa/version.py
supports https://github.com/mandiant/capa-rules/issues/642
> update rule compatibility doc

- CHANGELOG.md
- capa/features/extractors/dnfile_.py
- capa/features/extractors/dotnetfile.py
- capa/main.py
- scripts/show-capabilities-by-function.py
- tests/fixtures.py
> fix dotnet and pe format handling

- CHANGELOG.md
- capa/render/verbose.py
> render: verbose: fix rendering of scopes

- CHANGELOG.md
- capa/ida/helpers.py
> make read consistent with file object behavior

- CHANGELOG.md
- capa/features/extractors/viv/insn.py
> fix: don't extract invalid calls from features

- tests/test_main.py
> optimize tests to speed them up

- .github/mypy/mypy.ini
- CHANGELOG.md
- capa/ida/helpers.py
- capa/ida/plugin/README.md
- capa/ida/plugin/form.py
still a WIP, but looking for feedback/testing
likely pending some updates from #1291 wrt rule caching/saving
closes #1279 
closes #892
> feat: store results to database and UI updates

- CHANGELOG.md
- capa/version.py
- doc/release.md
> update to v5.0.0

- CHANGELOG.md
- capa/features/extractors/viv/function.py
> fix loop detection corner case

- CHANGELOG.md
- capa/features/common.py
- tests/test_match.py
> update OS to match OS_ANY against all supported OSes

- scripts/lint.py
Changed lint.py to use fstrings consistently.
> code style: update lint.py

- capa/main.py
Closes : https://github.com/mandiant/capa/issues/1349
> fix wrong indentation level for args.backend

- tests/fixtures.py
- tests/test_engine.py
- tests/test_fmt.py
- tests/test_freeze.py
- tests/test_helpers.py
- tests/test_main.py
- tests/test_match.py
- tests/test_optimizer.py
- tests/test_os_detection.py
- tests/test_pefile_features.py
- tests/test_result_document.py
- tests/test_rule_cache.py
- tests/test_rules.py
- tests/test_rules_insn_scope.py
- tests/test_scripts.py
- tests/test_viv_features.py
Updated Copyright from `tests` directory. This PR closes #1379 issue.
> Updated Copyright 

- capa/main.py
> main: fix variable shadowing module os

- tests/test_scripts.py
> tests: fix proto tests on windows

- CHANGELOG.md
- capa/version.py
- see https://github.com/mandiant/capa-rules/actions/runs/4607481552/jobs/8142058303, the one fail on `check mutex and exit` is a transient and inconsistent issue
> update to v5.1.0

- .github/ruff.toml
- .github/workflows/tests.yml
- capa/features/extractors/binja/insn.py
- capa/features/extractors/ida/insn.py
- capa/ida/plugin/form.py
- capa/main.py
- scripts/capa2yara.py
- setup.py
- tests/test_engine.py
- tests/test_function_id.py
- tests/test_rules.py
> Linting with ruff 

- .github/workflows/tests.yml
> Only test BN on non-forks

- .github/workflows/tests.yml
> Don't test BN - attempt 3

- capa/main.py
The updated layout will only include dictionaries for functions that have at least one basic block in matched_bbs. This improvement will reduce the amount of un-referenced data in the JSON document, making it more concise and efficient.
Closes #1314
> Improved layout to exclude functions with no basic block.

- CHANGELOG.md
- capa/helpers.py
- capa/main.py
- scripts/lint.py
closes #749 
Reopening Accidentally closed PR #1481
> Add redirect print to tqdm for capa main

- .gitmodules
- CHANGELOG.md
- README.md
- capa/features/common.py
- capa/features/extractors/base_extractor.py
- capa/features/extractors/cape/extractor.py
- capa/features/extractors/cape/file.py
- capa/features/extractors/cape/global_.py
- capa/features/extractors/cape/helpers.py
- capa/features/extractors/cape/process.py
- capa/features/extractors/cape/thread.py
- capa/features/insn.py
- capa/rules/__init__.py
- tests/fixtures.py
this is an initial PR for adding the CAPE extractor, it addresses issue #1535, #1536, #1537 and #1538.
> add the CAPE feature extractor

- CHANGELOG.md
- scripts/linter-data.json
ref: https://github.com/mandiant/capa-rules/pull/776
thanks again to @kn0wl3dge for the script!
> update att&ck/mbc data via script

- .github/workflows/publish.yml
- .github/workflows/tests.yml
- CHANGELOG.md
- capa/helpers.py
- capa/ida/plugin/README.md
- capa/main.py
- setup.py
> bump minimum python version to 3.8

- CHANGELOG.md
- capa/main.py
- scripts/lint.py
- scripts/profile-time.py
> main: don't leave behind traces of the progress bar

- tests/fixtures.py
update `NtQueryValueKey` feature count.
> cape tests bugfix

- capa/features/address.py
- capa/features/extractors/cape/extractor.py
- capa/features/extractors/cape/file.py
- capa/features/extractors/cape/global_.py
- capa/features/extractors/cape/thread.py
- capa/features/extractors/helpers.py
- capa/features/freeze/__init__.py
- capa/render/verbose.py
- scripts/show-features.py
- tests/fixtures.py
There are mostly inspired from looking at a comparison from a fabricated CAPE JSON result and a vivisect capa extraction.
Plus some other things I came across. Happy to discuss anything and just take the best/desired functionality from this PR.
updated show-features output for thread-level features:
> enhance various dynamic-related functions

- .github/ruff.toml
- CHANGELOG.md
- capa/features/address.py
- capa/features/extractors/base_extractor.py
- capa/features/extractors/cape/extractor.py
- capa/features/extractors/cape/file.py
- capa/features/extractors/cape/helpers.py
- capa/features/extractors/cape/process.py
- capa/features/extractors/cape/thread.py
- capa/features/extractors/null.py
- capa/features/freeze/__init__.py
- capa/main.py
- scripts/show-features.py
- tests/fixtures.py
- tests/test_static_freeze.py
This PR adds addresses for processes and threads, which is a prerequisite for adding dynamic feature extraction to main.
TaskList:
> add process and thread addresses

- .github/flake8.ini
- capa/features/extractors/binja/basicblock.py
- capa/features/extractors/binja/extractor.py
- capa/features/extractors/binja/insn.py
- capa/features/extractors/dnfile/extractor.py
- capa/features/extractors/dnfile/helpers.py
- capa/features/extractors/dnfile/types.py
- capa/features/extractors/elf.py
- capa/features/extractors/ida/helpers.py
- capa/features/extractors/ida/insn.py
- capa/features/extractors/strings.py
- capa/features/extractors/viv/indirect_calls.py
- capa/features/extractors/viv/insn.py
- capa/ida/plugin/cache.py
- capa/ida/plugin/form.py
- capa/ida/plugin/hooks.py
- capa/ida/plugin/item.py
- capa/ida/plugin/model.py
- capa/ida/plugin/view.py
- capa/main.py
- capa/render/vverbose.py
- capa/rules/__init__.py
- pyproject.toml
- scripts/capa2yara.py
- scripts/import-to-bn.py
- scripts/lint.py
- scripts/profile-memory.py
- tests/test_rule_cache.py
> introduce flake8-simplify

- capa/features/extractors/ghidra/file.py
- capa/features/extractors/ghidra/function.py
- capa/features/extractors/ghidra/helpers.py
- capa/features/extractors/viv/function.py
- capa/main.py
Implements #1509 Ghidra Function Feature Extraction
> Ghidra: Function Feature Extraction

- pyproject.toml
> introduce flake8-use-pathlib

- .github/workflows/tests.yml
> ci: use latest python for best performance

- .github/ruff.toml
- CHANGELOG.md
- tests/conftest.py
- tests/test_binja_features.py
- tests/test_dnfile_features.py
- tests/test_dotnet_features.py
- tests/test_dotnetfile_features.py
- tests/test_freeze.py
- tests/test_function_id.py
- tests/test_main.py
- tests/test_pefile_features.py
- tests/test_proto.py
- tests/test_result_document.py
- tests/test_viv_features.py
> tests: make fixtures available via conftest.py

- CHANGELOG.md
- capa/features/extractors/elffile.py
- tests/test_elffile_features.py
closes #1607
closes #1608 
In below screenshot right side shows the list of import symbols extracted based on current code and left shows list of export and import symbols extracted based on updated code.
> ELF: Implement file import and export name extractor

- CHANGELOG.md
- capa/features/common.py
- capa/features/freeze/__init__.py
- capa/features/freeze/features.py
- capa/ida/plugin/form.py
- capa/render/json.py
- capa/render/proto/__init__.py
- capa/render/result_document.py
- capa/render/vverbose.py
- pyproject.toml
- scripts/bulk-process.py
- scripts/proto-to-results.py
- tests/test_result_document.py
> bump pydantic to 2.1.1

- scripts/lint.py
> lint.py: add default backend

- capa/helpers.py
- capa/main.py
> fix detection of CAPE reports

- capa/rules/__init__.py
- tests/test_rules.py
- tests/test_rules_insn_scope.py
> rules: add scope terms "unsupported" and "unspecified"

- scripts/lint.py
This PR updates the rule linting for the new scopes format. See PR: https://github.com/mandiant/capa-rules/pull/816
> Update the rules linter

- .github/workflows/tests.yml
> ghidra hotfix: fix ghidrathon download

- .github/workflows/tests.yml
> ghidra: update CI to use /Ghidra/Extensions

- CHANGELOG.md
- capa/features/extractors/binja/function.py
- capa/main.py
- tests/fixtures.py
- tests/test_binja_features.py
> Update to binja 3.5

- CHANGELOG.md
- capa/features/extractors/binja/file.py
- capa/features/extractors/binja/function.py
- capa/features/extractors/binja/insn.py
- tests/test_binja_features.py
> binja: add support for symtab names. Fix #1504

- CHANGELOG.md
- capa/features/extractors/binja/file.py
- capa/features/extractors/binja/helpers.py
- tests/test_binja_features.py
> binja: add support for forwarded exports

- capa/render/vverbose.py
> improve vverbose rendering

- capa/main.py
missed update in https://github.com/mandiant/capa/pull/1868/files
> only check and display file limitation once

- capa/main.py
> set os, arch, format in meta table

- capa/render/default.py
> render: show human readable flavor name

- CHANGELOG.md
- pyproject.toml
> fix setuptools package discovery

- CHANGELOG.md
- capa/version.py
> update to v7-beta

- capa/ida/plugin/form.py
minor bugs and improvements for saving a rule
> fix rule display and save functionality

- capa/ghidra/README.md
- capa/ghidra/capa_explorer.py
> update Ghidra integration

- scripts/lint.py
- tests/test_scripts.py
> lint: get backend from format

- README.md
> Update blog links

- CHANGELOG.md
- capa/features/freeze/__init__.py
potentially causing circular import errors
> freeze: remove unused import

- CHANGELOG.md
- capa/version.py
> update to v7.0.1

- capa/capabilities/dynamic.py
- capa/capabilities/static.py
> capabilities: don't show progress bar when stderr is redirected to a file

- .github/workflows/tests.yml
> update to Ubuntu 22.04 for Binary Ninja tests

- CHANGELOG.md
- capa/render/default.py
- capa/render/utils.py
- tests/test_render.py
Closes #843.
<details><summary>Output looks something like this:</summary>
</details>
> render maec/* fields

- CHANGELOG.md
- capa/features/common.py
see https://github.com/mandiant/capa-rules/pull/907#issuecomment-2154400186
> features: add aarch64 arch

- .github/workflows/build.yml
- .github/workflows/tests.yml
- CHANGELOG.md
> Update macos 12

- capa/features/extractors/cape/global_.py
Please describe the changes in this pull request (PR). Include your motivation and context to help us review.
Fix incomplete f-strings
Please mention the issue your PR addresses (if any):
closes #2153
-->
> Fix incomplete f-strings

- scripts/show-capabilities-by-function.py
> scripts/show-capabilities-by-function.py: fix incorrect function address

- .github/ruff.toml
> #2244 Issue: Update old deprecated variables

- .github/workflows/build.yml
- CHANGELOG.md
Closes https://github.com/mandiant/capa/issues/2270
> Skip build checks on documentation updates

- README.md
> readme: add quick links to header

- capa/main.py
closes #2183
open to feedback on this item
> cli: add note about capa explorer web to CLI help text

- requirements.txt
This PR adds msgspec to the `requirements.txt` file
closes #2359
> Add msgspec to requirements.txt

- CHANGELOG.md
- capa/features/extractors/ida/helpers.py
> fix byte search IDA Pro 7.5 compatability

- doc/release.md
> add update homepage entry

- CHANGELOG.md
- pyproject.toml
> pyproject.toml: bump min python version to 3.8.1

- .github/workflows/build.yml
- CHANGELOG.md
> pyinstaller: use Python 3.12 for standalone build

- .github/dependabot.yml
> Update dependabot.yml to ignore patch versions

- web/explorer/src/utils/rdocParser.js
> capa Explorer Web: fix import features

- web/explorer/src/components/NavBar.vue
closes #2420 
please note, the submit feedback link will redirect to GitHub sign-in page if the user is not logged in
> capa Explorer Web: add provide feedback button

- .github/workflows/web-deploy.yml
- .github/workflows/web-tests.yml
> Update Node checkout Actions

- web/public/index.html
> add v7.4.0 info

- CHANGELOG.md
- capa/ida/plugin/form.py
> fix bug preventing save of capa results

- .github/workflows/changelog.yml
- CHANGELOG.md
> ci: skip changelog.yml when PR author is `dependabot`

- .github/workflows/build.yml
- .github/workflows/tests.yml
- CHANGELOG.md
> Use macOS 13

- CHANGELOG.md
- capa/features/extractors/binja/basicblock.py
- capa/features/extractors/binja/extractor.py
- capa/features/extractors/binja/function.py
- capa/features/extractors/binja/insn.py
This fixes https://github.com/mandiant/capa/issues/2516
> binja: move the stack string detection to the function level

- CHANGELOG.md
- capa/version.py
- web/public/index.html
> update to v8.0.1

- CHANGELOG.md
- capa/features/extractors/elffile.py
> elffile: fix handling of symbols without a name

- capa/features/extractors/ghidra/insn.py
- capa/ghidra/helpers.py
Updating the Ghidra backend's check for security cookies and fixing an import that was breaking the implementation. Addressing the issue detailed in https://github.com/mandiant/capa/issues/2071
> Ghidra - Fix Security Cookie Check - #2071

- CHANGELOG.md
- capa/version.py
- web/public/index.html
went with v9.1.0 versus v9.0.1 due to the number of fixed rules, which should be a nice experience improvement. 
> release v9.1.0

- CHANGELOG.md
- capa/features/extractors/cape/extractor.py
- capa/features/extractors/cape/file.py
- capa/features/extractors/cape/models.py
> cape: mark some fields as optional

- CHANGELOG.md
- tests/test_binja_features.py
> update binja core version

- .github/workflows/publish.yml
> update "publish package" workflow to 1.12.4

- .github/pyinstaller/pyinstaller.spec
- .github/workflows/build.yml
- .github/workflows/tests.yml
- CHANGELOG.md
> fix build issues discovered during and after v9.2.0 release

- tests/test_binja_features.py
> binja: update core version info check
